
= Parties

== Economic operator

The economic operator is the party submitting the T19 - Qualification and the recipient of the T020 - Qualification Reception Confirmation, and is any natural or legal person or public entity or group of such persons and/or entities, including any temporary association of undertakings, which offers the execution of works and/or a work, the supply of products or the provision of services on the market. The T020 - Qualification Reception Confirmation must be returned to the Main Qualifying Party which submitted the T19 - Qualification.

[source,xml,indent=0]
.Economic operator is represented in UBL 2.2 using ReceiverParty

----
include::../files/QualificationResponse-doc.xml[tags=ReceiverParty]
----

== Contracting Body

The contracting body is the contracting authority or contracting entity who is buying supplies, services or tendering works.

[source,xml,indent=0]
.The contracting body is represented in UBL 2.2 using the SenderParty:

----
include::../files/QualificationResponse-doc.xml[tags=SenderParty]
----
