[[use-case-1]]
== Use case 1


[cols="1,5",options="header",]
|====
|*Use Case number* |1
|*Use Case Name* |A central unit has been given the task to accomplish a tender for the group on office supplies.  
|*Use Case Description* a|
On behalf of many municipalities or governmental entities a central unit has been given the task to accomplish a tender for the group on office supplies.

The call for tender includes a structured pre-award catalogue request with the needs for the group. The EO (supplier) that prepares the tender downloads 
or receives the catalogue request as part of the tendering documents. The pre-award catalogue request is containing descriptions of product and services 
the group needs in a generic way, e.g. blue pen.

Supplier choose their own products or services that fulfill the requirement and make use of a supplier eSubmission system to fill out the requested 
information as product number, product description, UoM (unit of measure) code, price, link to pictures and labels for environmental and social labels 
if required and so on. They can reuse generic information the central unit has included in the pre-award catalogue request as classification codes as 
UNSPSC, CPV or eCl@ss.

After finalizing the pre-award catalogue they include the catalogue together with other structured documents as ESPD or non-structured documents as PDF 
into the system. The system prepares for submission towards the tender systems by sending the bid package to the access point connected.

When the CA receives the pre-award catalogues through their access point, from different suppliers, they lock down the offers as part 
of the bid packages. When time for open the bids, tendering system import the pre-award catalogue xml files into their valuation service and find the 
best offer of products and/or services.

The central unit import the catalogue into their catalogue tool and checks the quality. According to the contract, the supplier is sending a post-award 
catalogue that’s compared towards the pre-award catalogue from the tender. When the catalogue is ok the central unit sends it out of their access point, 
based on a distribution list in the catalogue tool. The different municipalities or governmental entities are receiving the approved pre-award catalogue 
in their catalogue tool connected to their eProcurement system. When the catalogue is already approved, the system can automatically display the catalogue 
content in the eProcurement search engine used by the different entities buyers.

|*Parties involved* a|
Contract Authority (sender) (In UBL: ProviderParty) 

Economical Operator (receiver) (In UBL: ReceiverParty)

Despatch location (In UBL: SellerSupplierParty)

Consignee location (In UBL: ContractorCustomerParty)

|*Pre conditions* a|
The CA want to send a Catalogue Request to selected EOs that are relevant for this type of products. 
All EOs have before this qualified as suppliers in a different process.

|*Post conditions* a|
The Catalogue Request is received by the selected EOs.

|*Assumptions* a|
. The EO is qualified as a company in an earlier process.
. The EO can provide the type of products or services requested.

|*The flow* a|
. The CA selects which EOs they want to send a Catalogue Request to. 
. The CA creates a list of products or services they want to purchase.
. The CA forms a Catalogue Request and sends it to selected EOs.
. The EO receives the Catalogue Request and analyzes the content.
. The EO creates a Catalogue for the requested products containing item identification and price etc.
. The EO sends the Catalogue to the CA.
. The CA receives the Catalogue and starts the evaluation process.

|*Result* a|
. The Catalogue Request message helped the EO to create the Catalogue.
.. Faster.
.. With less work.
.. With less errors and misunderstandings.

. The Catalogue message helped the CA to select the best offer.
.. Faster since EOs are expected to return the Catalogue quicker.
.. With less work since all Catalogues are recived in the same format and no manual entry is needed.
.. With less errors and misunderstandings.

|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 1.
|====
