
= Document references

== Tender document reference

The tender reception notification contains the reference to the tender document sent by the economic operator. The contracting authority should refer to the tender by using the document hash and the hash algorithm method used.

DocumentReference Identifier for a Call for Tender Reference must be expressed in a UUID syntax (RFC 4122).

////
[source,xml,indent=0]
.DocumentHash

----
include::../{xml-doc-file}[tags=DocumentHash]
----
////
Document hash algorithm must be http://www.w3.org/2001/04/xmlenc#sha256[SHA-256].
////
[source,xml,indent=0]
.Document hash algorithm

----
include::../{xml-doc-file}[tags=HashAlgorithmMethod]
----

////

[source,xml,indent=0]
.Tender document reference (REM Evidence)

----
include::../{xml-doc-file}[tags=TenderDocumentReference1]
----

[source,xml,indent=0]
.Tender document reference (Tender)

----
include::../{xml-doc-file}[tags=TenderDocumentReference2]
----


== Document Type Code (REM Evidence)

The type of business document must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]. The code used to reference the REM-Evidence regarding the time of arrival of
a tender is 13 (Post receipt)

[source,xml,indent=0]
.Document Type Code
----
include::../{xml-doc-file}[tags=DocumentTypeCode1]
----

=== Issuer Party

Party, which issued the REM Evidence, usually the receiving access point which is not always the final receiving party of the message.

[source,xml,indent=0]
....
include::../{xml-doc-file}[tags=IssuerParty]
....

== Document Type Code (Tender)

The tender document received must also be included in the document reference element. Document Type
Code is coded according to code list 1001 issued by UN/CEFACT. For a complete list of all
the document types, see https://service.unece.org/trade/untdid/d99a/uncl/uncl1001.htm[UNCL 1001]. The code used to reference a tender is 310 (Offer / quotation)

[source,xml,indent=0]
.Document Type Code
----
include::../{xml-doc-file}[tags=DocumentTypeCode2]
----

=== Issuer Party

Identifier of the economic operator which issued the tender.

[source,xml,indent=0]
....
include::../{xml-doc-file}[tags=IssuerParty2]
....
