
= Key examples

The following examples show use cases illustrating how the {name-profile}  can be used.

== Prior Information Notice

*Example 1*

A contracting body sends a request to publish a prior information notice, the notice concerns the delivery of one hundred personal computer and the installation of administrative software. The notice contains also details about the project such as the place of performance, the duration and the estimated value of the procurement. All information about the contracting body are included in the notice. If the reducing time limit indicator is checked, the contracting body indicates that a call for tender with a reduced delay for submitting bids will be published. The economic operator will see from the notice the estimated date of publication of the contract notice.

*Example 2*

A contracting body has a procurement project and publishes a prior information notice to inform economic operators about a business opportunity. The notice presents details about the project (text description, NUTS codes for location, CPV code for procurement items). If the call for competition indicator is checked, interested operators may inform the contracting authority about their interest in the contract.

== Contract Notice
*Example 3*

A contracting body sends a request to publish a contract notice to the publication body. The publication body validates the notice. The notice concerns the delivery of one hundred personal computers and the installation of software. The notice contains also details about the project such as the place of performance, the duration and the estimated value of the procurement. All information about the contracting body are included in the notice. The publication body publishes the contract notice. Economic operators can see in the published notice, the address to access more information about the procurement project and the address to submit tenders or request to participate.

*Example 4*

A contracting body has a procurement project and publishes a contract notice to inform economic operators about the call for tenders. The notices present details about the project (text description, NUTS codes for location, CPV code for procurement items) and the procurement procedures (delay, award criterion, technical or financial capacities), so that economic operators can evaluate their interest in this business opportunity.

== Contract Award Notice

*Example 5*

A contracting body has awarded a contract and publishes a contract award notice to inform economic operators about the winner of the call for tender. The notice presents details about the procurement procedures (delay, award criterion, number of candidates) and the awarded contract.

*Example 6*

A Dutch contracting body received several bids from different European countries. After having evaluated the tenders, he informs all tenderers (successful and non-successful) of the award decisions giving reasons for this decision. As the last step in the procedure the contracting body publishes the contract award notice on the Dutch procurement platform and Tenders Electronic Daily (TED).
