
= Tender Encryption

The Call For Tenders (CfT) business document is used by the contracting authority to provide an economic operator with the latest updated procurement documents. Besides transporting procurement documents it MUST be used to transport the encryption certificate needed by the economic operator to encrypt his tender for submission. The method how to include the Encryption Certificates is desribed in link:/pracc/transactions/T004/index.html[T004 - section  5.5. Transport of encryption certificate via the Call For Tenders]

If the CfT business document provided an encryption certificate, the tender documents MUST be encrypted by the economic operator using that certificate.

The example provided in link:/pracc/transactions/T005/index.html[T005 - section  5.2.3 Attached documents and tender encryption] illustrates an attached and encrypted tender document, its hash and algorithm. Encrypted tender documents must use the file extension .p7m in  _<cbc:Filename></cbc:Filename>_. The attached tender document in the provided example is an unstructured .pdf file.

