[[parties-and-roles]]
= Parties and roles

The table below gives the definitions of the parties and roles incolved in transport execution planning.

[cols="2,8",options="header",]
|====
|Parties |Definition
|*Customer* a|

The customer is the legal person or organisation who is in demand of a product or service.
Examples of customer roles: buyer, consignee, debtor, contracting authority.

|*Supplier* a|

The supplier is the legal person or organisation who provides a product or service.
Examples of supplier roles: seller, despatch party, creditor, economic operator.

|*Carrier Party* a|

The carrier handles the physical delivery/transportation of the despatched shipment. Used if a third party is handling the physical transport.

|*Freight Forwarder Party* a|

An agent who acts on behalf of importers, exporters or other companies to organise the safe, efficient and cost-effective transportation of goods. In some cases, the freight forwarding company itself provides the service.

|*Despatch Party* a|

The Despatch Party is the person or organisation who provides (despatch) the goods or services. The role is carried out by the supplier or on behalf of the supplier. (Despatch Party is sometimes known as the Consignor or 3rd Party Logistics Providers).

|*Supplier Party* a|

The party where goods are to be collected from. The Despatch Party may be stipulated in a transport contract.

|*Seller Party* a|

The seller is the legal person or organisation who sells goods or services to the customer. The role is carried out by the supplier or on behalf of the supplier.

|*Buyer Party* a|

The buyer is the legal person or organisation who buys or purchases the goods or services. The role is carried out by the customer or on behalf of the customer.
|====

[cols="2,9",options="header",]
|====
|Roles |Definition
|*Consignor (UBL:DeliverySupplierParty)* a|

Consignor. Is the seller of the goods and is often referred to as the Seller or Shipper.

|*Consignee (UBL:DeliveryCustomerParty)* a|

The Consignee is the person or organisation to which the products will be shipped and who is taking possession. The role is carried out by the customer or on behalf of the customer.

|*Despatch Party (UBL:DespatchSupplierParty)* a|

The Despatch Party is the person or organisation who provides (despatch) the goods or services. The role is carried out by the supplier or on behalf of the supplier. (Despatch Party is sometimes known as the Consignor or Supply Party.

|*Buyer (UBL:BuyerCustomerParty)* a|

The Buyer is the legal person or organisation who buys or purchases the goods or services. The role is carried out by the customer or on behalf of the customer.

|*Seller (UBL:SellerSupplierParty)* a|

The Seller is the legal person or organisation who sells goods or services to the customer. The role is carried out by the supplier or on behalf of the supplier.

|*Freight Forwarder (UBL: FreightForwarderParty)* a|

Freight Forwarder an agent who acts on behalf of importers, exporters or other companies to organise the safe, efficient and cost-effective transportation of goods.In some cases, the freight forwarding company itself provides the service.

|*(UBL:TransportServiceProviderParty)* a|

The party offering the transport service based upon a request from a transport user.

The supplier is the legal person or organisation who provides a service.

Supplier: Carrier
Sometimes referred to as:
* Freight Forwarder
* Courier
* Rail Carrier
* Airline
* Shipping Line
* Road Haulier
* Courier
* GSA (General Sales Agent)
* NVOCC (Non vessel owner common carrier)


|*Finance Party Bank* a|

A provider of finance in a supply chain such as a Bank.

A seller consigns goods to a carrier in exchange for a bill of lading. The seller then provides the bill of lading to the bank in exchange for payment. The seller's bank exchanges the bill of lading for payment from the buyer's bank. The buyer's bank exchanges the bill of lading for payment from the buyer. The buyer then provides the bill of lading to the carrier and takes delivery of the goods.

|*Insurance Party* a|

Any business that has goods moving around either via own vehicles or external freight companies has a requirement for marine cargo insurance.  This form of insurance provides protection to companies if their goods sustain damage or loss whilst in transit by road, sea or air.

|====