[[descriptions]]
= Description of selected parts of the transaction

The transaction is based upon the definitions of {name-transaction-org} described in {link-profile}. Business terms, Business rules and code lists used are inherited from the following {link-bii3} and {eforms-specs} and {regrep} documents:

== Query Request: Parameter maxResults and startIndex

The Search Notice Request and Response support the ability to iterate over a large result set matching a query by allowing multiple QueryRequest requests to be submitted in succession such that each query requests a different subset of results within the result set. This feature enables the server to handle queries that match a very large result set, in a scalable manner also known as pagination.

[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[lines=2..14]
....

[cols="4,8", options="header"]
|===
| name
| description

| startIndex
| This attribute is used to indicate which result must be returned as the first result when iterating over a large result set. The default value is 0, which returns the result set starting with index 0 (first result).

| maxResults
| This attribute specifies a limit on the maximum number of results the sender wishes the query to return. A receiver of the request MUST return a result set whose size is less than or equal to the maxResults parameter depending upon whether enough results are available starting at startIndex. If the default value -1 is used, the receiver SHOULD return all the results.
| id
| Specifies the unique identifier for an Identifiable Search Notice Request. In case of different start index for same QueryRequest is used it is possible to use the same Search Notice Request identifier.
|===

[plantuml, pagination-seq-diagram, svg]
.Example of a request with maxResults set to 100.
....
include::../../../shared/pagination.PLANTUML[]
....

== Specification Identification
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=specification-identification]
....
<.> Identifier for the set of rules and transactions for a search notice request.
<.> The value for the specification identification is always "_urn:fdc:peppol.eu:prac:trns:t011:1.1_", just like in the given example.

== Business Process Type Identifier
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=business-process-type-identifier]
....
<.> Identifier for the business process context of the search notice response.
<.> The value for the business process type identifier is always "_urn:fdc:peppol.eu:prac:bis:p006:1.1_", just like in the given example.

== Issue Date Time
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=issue-date-time]
....
<.> Date and time when the request was being issued.
<.> The SlotValue type has to be DateTimeValueType. Stick to the format "_yyyy-mm-ddThh:mm:ss_" and add the timezone in the end (i.e. Z or +01:00). Values for seconds, and the timezone must be given.

== Sender electronic address
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=sender-electronic-address]
....
<.> The endpoint id is clarified in the type attribute of the slot.
<.> Fill the electronic sender address into this slot.

== Receiver electronic address
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=receiver-electronic-address]
....
<.> The endpoint id is clarified in the type attribute of the slot.
<.> Fill the electronic receiver address into this slot

== Response Option
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=response-option]
....
<.> You have to include the response option with its default option "_LeafClassWithRepositoryItem_" to allow for the response to include the required repository items.

== Query and Query Parameters
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=queryDefinition]
....
<.> You have to use the fixed value "_SearchNotice_" as Query Definition.

=== Keywords
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=keywords]
....
<.> All keywords are collected as one single string. Enter the keywords for the search as expecting it from a searchbar. Select keywords for any parameter of the search as if searching for a specific procedure.

This slot is optional and can only be included once.

=== Form Type
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=form-type]
....
<.> Select the type from the given collection. Into the type-attribute of the slot is to fill with the listID "_http://publications.europa.eu/resource/authority/form-type_".

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has to be of a xsi:type StringValueType. This slot is optional and can only be included once.

=== Notice Type
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=notice-type]
....
<.> Just like the form type, you may select the notice type, you want to search for. The ID of the list has to be "_http://publications.europa.eu/resource/authority/notice-type_" in the type attribute of the slot.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has to be of a xsi:type StringValueType. This slot is optional and can only be included once.

=== Classification
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=classification]
....
<.> The classification consists of the type of classification and the value. The type of classification is filled into the type-attribute in form of your listID ("_http://publications.europa.eu/resource/authority/cpv/cpv_" or "_http://publications.europa.eu/resource/authority/cpv/cpvsuppl_").
Therefore, the type of your classification has to be the same for each element. Into the value tag goes the selected CPV or CPVsuppl code for the search request.
<.> This would be an example of to different kinds of classifications searched for in the same request. The first one is a standard cpv code, and the second a cpvsuppl code. Both have to be put in different classification slots. In total there can be two classification slots, but each consists of multiple elements with various codes.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType, that you have to declare. The whole slot is optional.

=== Contract Nature
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=contract-nature]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/contract-nature_" has to be filled into the type-attribute of the slot.
<.> Each element has its own type, i.e. StringValueType, that you have to declare.
<.> The values were chosen to match the classification codes.

This slot is optional and can only be included once.

=== Place of Performance
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=place-of-performance]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/nuts_" has to be filled into the type-attribute of the slot. Each location is added in form of a standard NUTS-Code.

This slot is optional and can only be included once.

=== Estimated Value
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tag=estimatedValue]
....
<.> The slot for the estimated tender value consists of four different slots, which can all be added to specify the tender value. The slot as a whole is optional, as are each of the three slots in it.
<.> The first one is minimum, the minimal tender value you are looking for. It has to be declared as an integer.
<.> Corresponding to minimum, the second value you can search for in the tender value is the maximum. Just like the minimum the maximum tender value you are searching for is an integer.
<.> The third possible criteria is the currency. This one is a CollectionValueType you can enter more than one element. The values are selected from the list "_http://publications.europa.eu/resource/authority/currency_" which ID is deposited in the type-attribute of the slot.

This slot is optional and can only be included once. If Estimated Value is included at least one of minimum, maximum or currency has to be included as well. These can only be included once.

=== Procedure Type
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=procedure-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/procurement-procedure-type_" has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

This slot is optional and can only be included once.

=== Submission language
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=submission-language]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/language_" has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

This slot is optional and can only be included once.

=== Publication Date
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=publication-date]
....
<.> The first of four date slots. Here you can search for the date of publication. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time of the publication. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.
<.> The second slot can be filled with a possible end date and time of the publication. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.

This slot is optional and can only be included once.

=== Deadline Receipt Tenders
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=deadline-receipt-tenders]
....
<.> The second of four date slots. Here you can search for the deadline of receipt tenders. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline for receipt tenders. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.
<.> The second slot can be filled with a possible end date and time for the deadline for receipt tenders. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.

This slot is optional and can only be included once.

=== Additional Information Deadline
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=additional-information-deadline]
....
<.> The third of four date slots. Here you can search for the deadline of additional information. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline of additional information. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.
<.> The second slot can be filled with a possible end date and time for the deadline of additional information. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.

This slot is optional and can only be included once.

=== Deadline Receipt Requests
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=deadline-receipt-requests]
....
<.> The last of the four date slots. Here you can search for the deadline of receipt requests. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline of receipt requests. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.
<.> The second slot can be filled with a possible end date and time for the deadline  of receipt requests. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format ("_yyyy-mm-ddThh:mm:ss_", the timezone in the end (i.e. Z or +01:00)). Values for seconds, and the timezone must be given.

This slot is optional and can only be included once.

=== Notice Identifier
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=notice-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the id you get in your response.

This slot is optional and can only be included once.

=== Procedure Identifier
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=procedure-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the logical id you get in your response.

This slot is optional and can only be included once.

=== Procedure legal basis
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=procedure-legal-basis]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "legalBasis" has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.  Insert the id of the legal base from which you draw the procedure.

This slot is optional and can only be included once.

=== Reserved Participation
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=reserved-participation]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/reserved-procurement_" has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Choose if the procedure is only accessible for certain types of companies.

This slot is optional and can only be included once.

=== Suitable for SMEs
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=suitable-for-smes]
....
<.> As this slotValue is a boolean, please only insert true or false, if the procedure has to be suitable for small or medium-sized economic operators.

This slot is optional and can only be included once.

=== Winner economic operator name
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=winner-economic-operator-name]
....
<.> Insert the official name of the company which won the procedure.

This slot is optional and can only be included once.

=== Award criterion type
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=award-criterion-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The listID "_http://publications.europa.eu/resource/authority/award-criterion-type_" has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Some values cannot be combined with each other, so be careful in selecting each.

This slot is optional and can only be included once.

=== Buyer Information
[source,xml,indent=0]
....
include::{snippets-dir}/ExampleSearchNoticeRequest.xml[tags=information-about-buyer]
....
<.> This slot collects all the information about the buyer.
<.> Name of the buying company.
<.> The number of the organisation, as defined in each country.
<.> The address of the company - city.
<.> The address of the company - postcode.
<.> The id of each affected subdivision of the company, as selected from the code list. The listId "_http://publications.europa.eu/resource/authority/nuts_" has to be deposited in the type attribute of the slot. Multiple subdivision ids can be added.
<.> The country code of each affected country, as selected from the code list. The listId "_http://publications.europa.eu/resource/authority/country_" has to be deposited in the type attribute of the slot. Multiple country codes can be added.
<.> The legal type of the buying company, as selected from the code list. The listId "_http://publications.europa.eu/resource/authority/buyer-legal-type_" has to be deposited in the type attribute of the slot. Multiple legal types can be added.
<.> The main activity of the buying company, as selected from the code list. The listId "_http://publications.europa.eu/resource/authority/main-activity_" has to be deposited in the type attribute of the slot. Multiple activities can be added.

The whole slot is optional and can be included multiple times. If Buyer Information is included at least one of name, organisation number, city, postcode, organisation country subdivision, country code, legal type or main activity has to be included as well. These can only be included once.
