[[despatchadvicetypecode]]
= Despatch Advice Type Code

== Advice of despatch of goods
Despatch Advice Type Code 1, 101, 102 and 112 means that this transaction is sent before the transportation is started. 
The base code is "1", but the second part of the code can also hold a reference to the usecase that the Despatch Advice is representing. 
Usecases 01, 02 and 12 are relevant for this.

== Delivery Note
Despatch Advice Type Code 2, 203, 204, 205, 206, 207, 208, 209, 210 and 211 means that this transaction is sent after the 
transportation is finalized. The base code is "2", but the second part of the code can also hold a reference to the usecase.
Usecases 03 - 11 are relevant for this.

== Work statement
Despatch Advice Type Code 3, 303, 304, 305, 308, 309, 310 and 311 means that this transaction is sent after work has been finalized.
The base code is "3", but the second part of the code can also hold a reference to the usecase.
Usecases 03 - 05 and 08 - 11 are relevant for this.

== Return of Goods
Despatch Advice Type Code 4 means that this transaction is sent to return goods.

.Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=despatchadvicetypecode]
----