
= Benefits of the Tendering Message Response

The Tendering Message Response (TMR) is intended to inform the issuer of the following situations:

* The received message (or business document) contained fatal errors according to the relevant conformance and processing rules.

** _Result: The received message (or business document) will not be processed any further._

[IMPORTANT]
Due to legal framework conditions, there is a constraint to tolerate errors to a certain extent when receiving a tender, even if from a technical point of view, the message might have to be rejected. Especially tender rejections have to be kept to a minimum and must be based on valid reasons. These have to withstand judicial review.

* The received message (or business document) passed the validation of conformance and processing rules without any fatal errors but warnings.

** _Result: The received message (or business document) will be processed further. Eventual warnings are included to the Tendering Message Response._

* The received message (or business document) passed the validation of conformance and processing rules without any errors.

** _Result: The received message (or business document) will be processed further._

* The received message (or business document) has been correctly processed by the receiver even though it has not been validated for conformance. The receiver acknowledges that it has been received and identified as a valid business document.

** _Result: The received message (or business document) will be processed further._


