= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of {link-peppol} Pre-Award.
The specification herein is based on the {link-bii3} and the {link-BII107} and it is named:

&#8226; {name-profile}

The eTendering Message Response closely relates to the corresponding {link-PEPPOL-MLR} used in PEPPOL Post-Award.

NOTE: The {link-BII107} profile document is available from your national standardization body.

The intended scope for this profile includes public procurement, but the profile may also be used in Business to Business (B2B) relations.

This profile is intended to support transmission of electronic documents for processing in (semi-)automated processes. The legal requirements that were taken into account are requirements from European legislation, in particular the {2014-23-EU}, {link-eu-directive}[Directive 2014/24/EU]
and link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0025&from=EN[Directive 2014/25/EU]

:leveloffset: +1


include::TMRintroduction.adoc[]
include::benefit.adoc[]
include::errors-in-scope.adoc[]
include::errors-out-of-scope.adoc[]
include::parties-roles.adoc[]
include::business-requirements.adoc[]



:leveloffset: -1
