
= Implementation guidelines


{name-profile} is based on work done by {link-bii3}, and business rules and code lists used are inherited from the following {link-bii3} and {link-ubl-22} documents:

 urn:oasis:names:specification:ubl:schema:xsd:TenderWithdrawal-2
 urn:oasis:names:specification:ubl:schema:xsd:TenderReceipt-2

* {ubl-tender-withdrawal}[UBL Tender Withdrawal Schema] sent by the Economic Operator (the tenderer) to a Contracting Authority to withdraw a tender.
* {ubl-tender-receipt}[UBL Tender Receipt Schema] sent by a contracting party to an economic operator acknowledging receipt of a Tender or Tender Withdrawal.
* {link-profile} describes electronic messaging support for the business process of the withdrawal of a tender or of participation in a tendering process by an economic operator.

{link-peppol} {name-profile} business process includes 2 transactions:

* link:../../transactions/T013/index.html[T013 - Tender Withdrawal]
* link:../../transactions/T014/index.html[T014 - Tender Withdrawal Reception Notification ]
