
= Encryption of Qualification documents

The Call For Tenders (CfT) business document is used by the contracting body to provide an economic operator with the latest updated procurement documents. Besides transporting procurement documents it MUST be used to transport the encryption certificate needed by the economic operator to encrypt his qualification for submission. The method how to include the Encryption Certificates is desribed in link:/pracc/transactions/T004/index.html[T004 - section  5.5. Transport of encryption certificate via the Call For Tenders]

If the CfT business document provided an encryption certificate, the qualification documents MUST be encrypted by the economic operator using that certificate.

The example provided in link:/pracc/transactions/T019/index.html[T005 - section  5.3. Document References and Qualification Encryption] illustrates an attached and encrypted qualification document, its hash and algorithm. Encrypted qualifiation documents must use the file extension .p7m in  _<cbc:Filename></cbc:Filename>_. The attached qualification document in the provided example is an unstructured .pdf file.

