
[[descriptions]]
= Description of selected parts of the transaction

The transaction including business terms, business rules and code lists are based upon the definitions of {name-transaction-org} described in:

{name-profile-org}.

== Identifier

=== Qualification Response Identifier

The identifier enables positive referencing the transaction instance for various purposes including referencing between transactions that are part of the same process. Must be expressed as a UUID.

[source,xml,indent=0]
.Example of qualification response document identifier
....
include::../files/QualificationResponse.xml[tags=ID]
....
<.> A transaction instance must contain an identifier, being expressed in uuid syntax


== Response issue date and time

Response issue date/time must be sent.

Response issue date is a xsi:date data type and is specified as "YYYY-MM-DD" where:

* YYYY - four digits year
* MM - two digits month (01 to 12)
* DD - two digits day (0)

Response issue time is a xsi:time data type and is specified as "hh:mm:ss" where:

* hh - two digits of hour (00 to 23) (am/pm NOT allowed).
* mm - two digits of minute (00 to 59)
* ss - two digits of second (00 to 59)
* TZD - time zone designator (Z or +hh:mm or -hh:mm)

The response issue date and time refer to the date when of the issuance of the response.

NOTE: The response issue time must specify the time zone.

[source,xml,indent=0]
.Example of response issue date and time
....
include::../files/QualificationResponse.xml[tags=IssueDateTime]
....
<.> Format for the date has to be yyyy-mm-dd
<.> Format for the time has to be hh:mm:ssTZD, granularity down to seconds and timezone


== Party identification

=== Sender Party

The party sending a Qualification Response to the party that initiated the request to qualify for a Procurement.
The sender party corresponds to the contracting body.

[source,xml,indent=0]
.Example of contracting body as sender party
....
include::../files/QualificationResponse.xml[tags=SenderParty]
....
<.> Identifies the contracting body's electronic address and the scheme identifier for the electronic address
<.> Identifies the contracting body itself and the scheme identifier to resolve sender party's identifier
<.> Contains the contracting body's official name.

=== Receiver Party

The party who is supposed to receive the Qualification Response. This is the same party that initiated the request to qualify for a Procurement.
The receiver party corresponds to the economic operator who handed in the Qualification to which this Qualification Response refers to.

[source,xml,indent=0]
.Example of economic operator as receiver party
....
include::../files/QualificationResponse.xml[tags=ReceiverParty]
....
<.> Identifies the economic operator's electronic address and the scheme identifier for the electronic address
<.> Identifies the economic operator and the scheme identifier to resolve the receiver party's identifier
<.> Contains the reconomic operator's official name including the organization's legal form.


== Response Document Reference

The Response Document Reference contains a reference to the original Qualification Document that had been handed in by the Economic Operator (receiver party of this document) to qualify for the procurement.

[source,xml,indent=0]
.Example of Response Document Reference
....
include::../files/QualificationResponse.xml[tags=ResolutionDocumentReference]
....
<.> The response document reference must contain an identifier, being expressed in uuid syntax.


== Qualification Response Resolution

The qualification response resolution is the central part of any qualification response. It contains all information required to inform about the qualification result (rejected or accepted).

*The qualification response resolution returned with this transaction may be positive or negative*. It is expected to respond every rejection but it is also possible to respond any acceptance. If more than one lot have been aimed to qualify for and need to be responded, one qualification response resolution for each lot is expected.

[source,xml,indent=0]
.Example of Qualification Response Resolution
....
include::../files/QualificationResponse.xml[tags=QualificationResolution]
....
<.> Names the qualification result. If the result ist *false*, it states that the economic operator is not allowed to attend the further procurement process and the qualification response can alo be named as qualification rejection. Any qualification rejection is required to be answered. A positive answer resulting in *true* may also be given, but is not necessarily requested.
<.> If the qualification response contains a qualification rejection, the reason for rejection must be explained in one or more resolution elements. The qualification rejection resolution is expected be te described in plain text. At least one reason for rejection element must be provided. A positive answer may be sent without a specific resolution element.
<.> The date at which the decision expressed in this qualification rejection resolution was made.
<.> The ProcurementProjectLot referenced in this qualification response
<.> The ProcurementProjectLot's ID

