
= Key examples

The following examples show use cases illustrating how the {name-profile}  can be used.

*Example 1*

A tendering system is connected to a platform disseminating published notices via an agreed interface. Every night the tendering system sends a search request to the notices platform. The search request states the criteria for interesting business opportunities. The search on the platform results in several notices. The platform answers the search request by sending the matching notices to the tendering system. The tendering system informs all economic operators using his system about the interesting business opportunities.

*Example 2*

A broker offers economic operators information about interesting business opportunities. The economic operators can create a profile for business opportunities they are interested in. The broker uses the profiles to search for interesting business opportunites on several platforms disseminating published notices. The platforms return the notices to the broker, who provides the economic operators with the relevant notices and thus information on business opportunities.
