[[benefits]]
= Benefits

Peppol BIS pre-award catalogue will stimulate the service provider marked to develop services that covers tendering processes both for CAs and EOs. 
Pre-award catalogue together with tendering metadata transaction (trdm090) and confirmation message (trdm045) will:

* make it possible for the CA to evaluate products and services automatically through their tendering tools
* make it easier for the EOs to participate in different tendering processes
* save time for the EO to offer their products and services to a CA when the list of products and services are standardized and also when products 
and services are defined by Properties without knowing any item number.
* save time for the CA to have a standardized list of products and services
* save time for the CA to request a quote on non-standard products that are described by Properties or when Item numbers are unknown. 
* save time for the EO not needing to manually enter the Request For Quote’s (RFQ’s) all information from a PDF or similar. Less risk of errors and 
misunderstandings.  
* make it possible for EOs to use tools to pre-fill their information before the specific tender and send the offer in a structured way 
through {digital-european-programme} eDelivery (Peppol) infrastructure. The benefit is that an EO uses one tool in different tenders instead of dealing with different interfaces 
depending on which tool the CA uses.
* make it possible for the CA to use the pre-award catalogue in mini-competitions and re-opening of competitions
* make it possible for an EO to use the Peppol BIS pre-award catalogue xml when up-loading the tender in a 3-corner model on condition that tendering 
systems are compatible.
