= Formatting of notice object

PEPPOL transaction {name-transaction} describes a process that supports electronic messaging for the publication of notice. The profile is executed between a contracting authority or its representative and a publication entity to announce business opportunities and contract awards in public procurement procedures.

The PEPPOL transaction {name-transaction} only provides a container in which a notice object can be transported. The notice object attached to a publication request must be formatted according the rules described for https://ec.europa.eu/growth/single-market/public-procurement/digital/eforms_en[eForms]. The corresponding https://simap.ted.europa.eu/eforms[eForms Specifications] are maintained by the Publication Office and are not a specific subject to this BIS. As proposed by eForms, the associated notice must follow the syntax provided by the UBL document schemas:

{name-profile-org}

eForms were established under https://eur-lex.europa.eu/eli/reg_impl/2019/1780/oj[Commission Implementing Regulation (EU) 2019/1780].  The standard forms to be used for the publication of procurement notices and a clear representation of all information requirements that need to be taken into account when preparing a notice object can also be found at: https://ec.europa.eu/docsroom/documents/43488[2019/1780 - Extended Annex to the eForms Regulation].
