[[principles-and-prerequisites]]
= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of the Waybill.

[[despatch-advice-message-in-general]]
== Business process in scope

A Waybill is a document that provides specific information about a freight shipment, such as origin, destination, transportation route, and contact information for the shipper and receiver. Waybills can be used in shipping freight cargo by truck, train, plane, or boat.
The main activities supported by this message are:

*Transport* Full description of how the goods are packed. A delivery is taken to be a number of
items that are despatched as a single consignment to a single delivery address. The type of transport required for the despatch and delivery of the goods being shipped is also specified.

The waybill is a common term covering various terms used in different modes of transport, for example:

* Bill of Lading, Ocean Bill of Lading, or Sea Waybill is used in Sea freight
* Air Waybill or eAWB is used in Airfreight
* Consignment Note (CMR or eCMR) is used in Road
* Rail Transport Document CIM and SGMS are used in Rail

:leveloffset: +1

include::parties.adoc[]

include::otherconcepts.adoc[]

//include::requirements.adoc[]

:leveloffset: -1
