[[principles-and-prerequisites]]
= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of the Waybill.

[[despatch-advice-message-in-general]]
== Business process in scope
The Waybill message is used in the fulfilment process by the Seller party to notify the Carrier about, the despatch and required delivery service required for the goods being sent, as well as details about the goods for cross checking with the order and ultimately the Waybill is used for declaring how the despatched goods are transported.

The main activities supported by this message are:

*Transport* Full description of how the goods are packed. A delivery is taken to be a number of
items that are despatched as a single consignment to a single delivery address. The type of transport required for the despatch and delivery of the goods being shipped is also specified.

The waybill is a common term covering various terms used in different modes of transport, for example:

* Bill of Lading, Ocean Bill of Lading, or Sea Waybill is used in Sea freight
* Air Waybill or eAWB is used in Airfreight
* Consignment Note (CMR or eCMR) is used in Road
* Rail Transport Document CIM and SGMS are used in Rail

:leveloffset: +1

include::parties.adoc[]

include::otherconcepts.adoc[]

//include::requirements.adoc[]

:leveloffset: -1
