[[principles-and-prerequisites]]
= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of the Waybill.

A Waybill is a document that provides specific information about a freight shipment, such as origin, destination, transportation route, and contact information for the shipper and receiver. Waybills can be used in shipping freight cargo by truck, train, plane, or boat.

Waybill is a common term covering various terms used in different modes of transport, for example:

* Bill of Lading, Ocean Bill of Lading, or Sea Waybill is used in Sea freight
* Air Waybill or eAWB is used in Airfreight
* Consignment Note (CMR or eCMR) is used in Road
* Rail Transport Document CIM and SGMS are used in Rail

[[waybill-in-general]]
== Business process in scope
The processes covered by this profile are:

* The *Waybill* is issued by the party who undertakes to provide transportation services, or undertakes to arrange for their provision, to the party who gives instructions for the transportation services (shipper, consignor, etc.). 

The main activities supported by this message are:

* The type of transport required for the despatch and delivery of the goods being shipped. The means of transport, routing and arrival details.

:leveloffset: +1

include::parties.adoc[]

include::otherconcepts.adoc[]

//include::requirements.adoc[]

:leveloffset: -1
