[[environmental-data]]
= Environmental data

The environmental data on header level resides within the OriginalDespatchTransportationService element and are 
.Transport Service Code, which is set to a fixed value of FuelReport since this is the only current application
.Transport Equipment, where the fuel consumption and related information resides for the transport
.Environmental Emission, that can contain CO2 and other emissions related to the transport or other service that consumes fuel.

[[fuel]]
== Fuel

The fuel consumption and related information regarding the fuel type to be used to caculate emissions tor the tansport or other service that consumes fuel.

Example:

[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-4.xml[tags=fuel]
----

[[environmental-emission]]
== Environmental Emission

Caculated envionmental emissions related to the transport or other related service that consumes fuel.

Example:

[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-4.xml[tags=environmentalemission]
----