= Notificaton procedures

Many pre-award opportunities first become visible to the economic operators in the form of notices describing upcoming or current procurement procedures (prior information notices or contract notices). At the end of such procedures a notice is published (contract award notice) notifying the result of the procedure.

eNotification covers the electronic transfer of electronic public procurement notices for publication and dissemination with the ultimate aim of opening business opportunities. eNotification profiles are addressed to all those who exchange procurement notices for publication and further information processing. The profiles are therefore generally addressed to eTendering Plattform Providers, Contracting Bodies, publishers, print shops, information brokers or monitoring or statistical services. eNotification can be carried out at various levels and between different levels (regional, state, European etc). The legal obligation of publishing notices at the correct level is the responsibility of the contracting bodies.

The content of the notices described in eNotification profiles are principally based on eForms that were established under {eform-reg}, which was published on 25 October 2019, and upon {2014-23-EU}, {2014-24-EU} and {2014-25-EU} and their annexes, particularly the {eform-annex} to be used for the publication of procurement notices. eForms are at the core of the digital transformation of public procurement in the EU. Through the use of a common standard and terminology, they can significantly improve the quality and analysis of data. Well-implemented eForms increase the ability of businesses and other organisations to find opportunities. They will also reduce the administrative burden for buyers, increase the ability of governments to make data-driven decisions about public spending, and make public procurement more transparent.

The publication of a Prior Information Notice, Contract Notice and Contract Award Notice describes the communication between a contracting body or his representative and a publisher. In the EU, {eforms-specs} are used to publish notices on Tenders Electronic Daily—an online portal for public procurement notices from across the EU. On the national level public procurement decision makers can benefit from {eforms-specs} through tailoring and defining a national approach to the various aspects of eForms, such as also using them for contracts below thresholds, considering different policies and requirements.

The {name-profile} supports a process by which a notification platform can be searched along a set of parameters to find any relevant notices on a query with relation to its metadata required by the further processing of PEPPOL eTendering profiles. The transactions, specified in {name-profile} are intended to be exchanged between the tendering systems of publishers but they can be adopted by any Business to Government (B2G), Government to Government (G2G) and Business to Business (B2B) relation. Since the {name-profile} provides access to Open Data, it also provides possibilities for the establishment of new business models that allow monitoring, the provision of statistical information or easy access for economic operators to relevant notices from different eTendering and Notification platforms. In order to execute the {name-profile} , it is necessary that the parties have PEPPOL eDelivery in place to enable them to send and receive the transactions in a secure way. The content model of the transactions is based on the EU-wide {eforms-specs} standard. In this way it is possible that any notification platform as well as procurement systems of economic operators and contracting bodies are based on the same information and process models, which makes them more interoperable.

The process by which notices can be searched for on a given platform is described in {name-profile}. The profile is based on CEN WS/BII 3 {name-profile-org}. For the purpose of electronic tendering, the {name-profile} plays a significant role. When the contracting body has published a notice, the interested economic operators who finds it may subscribe to this procedure by obtaining tendering information using PEPPOL P001 - Procurement procedure subscription. Thereby, the {name-profile} delivers necessary organisational and technical information for a PEPPOL P001 - Procurement procedure subscription.
