[[parties]]
= Parties

The following parties/roles may be specified in the message.
The same actor may play more than one role depending on the handling routine.

[[sender-party]]
== Sender (SenderParty)
The Sender is the party who sendes the weighing statement (e.g. Weighing Station, Shipper, Freight Forwarder, Carrier, ...).

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=sender-party]
----

[[receiver-party]]
== Receiver (ReceiverParty)

The Receiver is the party receiving this weight statement (e.g. Carrier, Terminal Operator, ...). 

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=receiver-party]
----

[[weighing-party]]
== Weighing party (WeighingParty)

The Weighing party is the party executing the weight measure (e.g. Weighing Station).

The Weighing party  is optional information in the Weight statement.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=weighing-party]
----

[[shipper-party]]
== Shipper (ShipperParty)

The party playing the role of the Shipper (BCO, FF or NVOCC) who is responsible for the VGM (e.g. according the SOLAS Convention).

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=shipper-party]
----
