
= Scope

This guide aims to provide insight into transaction details for the transaction model {name-transaction-org} of {link-profile}.
It is a transaction description, meant to be a standalone description to be used as a part of one or more procurement profiles.
It describes syntax mappings, requirements, rules and use case with example.

The transaction, specified in {name-transaction} is intended to be exchanged between between a requester and a data provider. In order to facilitate eTendering this could be for example the tendering systems of an economic operators and the notification platform used by a contracting bodies. In order to execture the transaction, is expected that the parties have connected their systems to the internet, and that they have middleware in place to enable them to send and receive the transactions in a secure way, using an agreed syntax.

The content model of the transactions can also be used in procurement platforms or portals, so that these platforms as well as procurement systems of economic operators and contracting bodies are based on the same information and process models, which makes them more interoperable. Even if platforms are not technically interoperable, the content model facilitates understanding the call for tender documents and to participate in the tendering process.
