
= Interoperability

This {link-peppol} BIS structure is based on the link:https://ec.europa.eu/isa2/home_en[European Interoperability Framework 2.0].

It applies the Framework as follows:

. Legal Interoperability
* Legal:
** {link-eu-directive}[Directive 2014/24/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0025&from=EN[Directive 2014/25/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014R0910&from=EN[Regulation 910/2014]

. Organizational interoperability
* Organization (Organization/Business):
** {link-bis} support only B2G
** {link-bis} support cross border, regional and domestic tendering procedures in EU and EEA
** {link-bis} can function as a standardized EDI agreement within a trading community
** {link-bis} support linking of business processes within the sending and receiving organization.

* Organization (Process):
** {link-bis} support a set of “common business processes” that are assumed to be supported by most enterprises whether public or private. These are processes that are used widely or understood as being relevant for most companies.
** The current scope of the {link-bis} and guidelines include processes that support the main flow of open procedures such publication of notices, search of notices, calls for tenders, tenders and awarding notifications. During these processes additional support processes may be executed between contracting bodies and economic operators, such as procurement procedure subscription, call for tenders’ questions and answers, tender withdrawal or tender clarifications.
** The {link-OpenProcedure} describes the choreography to execute open procedures using Peppol. Thus, the Notification & Open Procedure Guideline is a procedural specification. The guideline does not define individual transactions but it refers to Peppol several BISs and underlying standards, in which the transactions and the transaction information requirements are listed and defined. Even though the guideline is based on a set of Peppol BISs, its contents are derived from the agreement {BII37} of the CEN Workshop on Business Interoperability Interfaces for Public Procurement in Europe .



. Technical interoperability
* Technical Interaction (Process and semantic implementation):
** Use of transport specifications are described in the {link-eDelivery}
** Use of cryptographic specifications are described in the {link-eDocument}
