
= Tendering procedures

This section provides a brief overview about the notification and tendering procedures and their associated Peppol BIS and transactions. The illustration thereby points to the relevant Peppol BISs that depict a particular business process. Additionally, the guideline references the underlying {link-bii3} Workshop Agreement. The CEN BII3 workshop is a standardisation initiative within CEN (European Committee for Standardisation). It provides a framework for interoperability in pan-European electronic transactions expressed as a set of technical specifications ("Profiles") .

The profiles provided by CEN BII3 and Peppol are designed to facilitate effective public e-procurement based on a modular approach for implementation, with a focus on global interoperability. Thereby, BII profiles can be seen as “agreements” on message contents and business processes and are the baseline for many Peppol BISs which add specific technical implementation perspectives that are further illustrated in section 6. Thus, the CEN profile descriptions rather focus on the core information elements that typically cater to the majority of user requirements applicable across Europe and lower the need for detailed bilateral agreements between the trading partners whereas Peppol provides a framework for their implementation and adaption.

*Notification procedures*

Official notification through publishing bodies is part of many procurement procedures. Many pre-award opportunities first become visible to the economic operators in the form of notices describing upcoming or current procurement procedures (prior information notices or contract notices). At the end of a procedure, a contract award notice about the result of the procedure is published.

eNotification covers the transfer of electronic procurement notices for publication and dissemination with the ultimate aim of opening business opportunities. eNotification profiles are addressed to all those who exchange procurement notices for publication and further information processing. eNotification is therefore generally addressed to eTendering Plattform Providers, Contracting Bodies, publishers, print shops, information brokers or monitoring or statistical services. eNotification can be carried out at various levels and between different levels (regional, state, European etc). The legal obligation of publishing notices at the correct level is the responsibility of the contracting bodies.

The content model of procurement notices in Europe is based on {eform-reg} and upon {2014-23-EU}, {2014-24-EU} and {2014-25-EU} and their annexes, particularly the annex describing the standard forms to be used for the publication of procurement notices. eForms are at the core of the digital transformation of public procurement in the EU. Through the use of a common standard and terminology, they can significantly improve the quality and analysis of data. Well-implemented eForms increase the ability of businesses and other organisations to find opportunities. They will also reduce the administrative burden for buyers, increase the ability of governments to make data-driven decisions about public spending, and make public procurement more transparent.

eNotification covers the electronic transfer of electronic notices for publication and dissemination services. The publication of notices is executed between a contracting body or his representative and a publisher. CEN WS/BII 3 profiles {BII14} (CWA 17026-102), {BII10} (CWA 17026-101) and {BII43} (CWA 17026-103) describe the exchange of notices between a contracting body or his representative and a publisher. In Peppol, these profiles are covered by the Peppol BIS {P008} which provides electronic messaging support to publish a prior information notice, a contract notice or a contract award notice. Thus, Peppol BIS {P008} helps contracting bodies to announce business opportunities and contract awards in public procurement procedures.

In the EU, eForms are used to publish notices above threshold on Tenders Electronic Daily (TED)—an online portal for public procurement notices from across the EU. On the national level public procurement decision makers can benefit from eForms through tailoring and defining a national approach to the various aspects of eForms, e.g. using them for contracts below thresholds, considering different policies and requirements.

The Peppol BIS {P006} supports a process by which a notification platform can be queried along a set of parameters to find relevant notices and related metadata required by other Peppol BISs. The profile is based on CEN WS/BII 3 Profile {BII45}  (CWA 17026-104:2016). The transactions, specified in BIS {P006} are intended to be exchanged between eTendering systems and Publication Bodies but they can be adopted by many other actors. Since the {P006} provides access to Open Data, it also provides possibilities for the establishment of new business models that allow monitoring, the provision of statistical information or easy access for economic operators to business opportunities in different countries across different eTendering and eNotification platforms.

In order to execute the Peppol BIS {P008} and Peppol BIS {P006}, it is necessary that the parties have Peppol eDelivery in place to enable them to send and receive the transactions in a secure way. Implementers must also support {eforms-specs} content model because the transactions are based on the EU-wide eForms standard.

*Tendering procedures*

For the purpose of initiating electronic tendering via Peppol, the Peppol BIS {P006} plays a significant role. When the contracting body has published a notice, the interested economic operators who finds it may want to subscribe to this procedure by using Peppol {P001} based on {BII46}. Thereby, the Profile {P006} delivers necessary organisational and technical information to identify the procedure and contracting authority. This information is required because the request for procurement procedure subscription must be directed to the entity responsible for the procurement procedure.

eTendering can be put in place using different procedures, depending on the value and the type of the contract to be awarded, on the legal nature of the contracting body and on specific member state national legislation ({2014-24-EU} art. 26). Article 26 to 32 from {2014-24-EU} and article 43 to 50 from {2014-25-EU} describe the different tendering procedures that can be used by contracting bodies. For the purpose of electronic tendering, some of these procedures have been described in CEN WS/BII 3 {BII37} (CWA 17027-106) and CEN WS/BII 3 {BII39} (CWA 17027-108).

In open procedures, any economic operator can access the tender documents (including the call for tenders) and submit a tender before the time expires, without any previous assessment of their capabilities. In restricted and negotiated procedures and in a competitive dialogue the interested economic operators must submit a request to participate in order to be invited in the tendering process by the contracting body. When the contracting body has published a notice, the interested economic operators may subscribe (unscubsribe) to obtain (not obtain) tendering information using profile CEN WS/BII 3 {BII46} (CWA 17027-111) covered by Peppol BIS {P001}. Restricted and negotiated procedures require sending the invitation to tender (profile CEN WS/BII 3 {BII52} (CWA 17027-117) to the identified candidates.

Once the interested economic operator has subscribed to an open procedure, the contracting authority provides the procurement documents by using Peppol BIS {P002}. The BIS P002 is based on CEN WS/BII 3 {BII60} (CWA 17027-123) and CEN WS/BII 3 {BII47} (CWA 17027-112) and provides the call for tender documents. It can be repeated at any time until the tender submission deadline to receive the latest version of the procurement documents. Additionally, contracting authorities must push updates to the economic operators that subscribed to a procedure.

Within the call for tenders, contracting authorities must inform economic operators how to qualify for the procedure. This may be done by an European Single Procurement Document (ESPD) defined by the {espd-reg} for which Peppol develops the BIS ESPD 3.0 based on the {espd-edm}. Additionally, call for tenders may include pre-award catalogue information to describe products and services in a common format allowing economic operators to send offers in a structured way and contracting authorities to evaluate products and services automatically through their tendering tools. The Peppol {preaward-cat} can be used for this purpose and was defined according to the CEN WS/BII 3 Profile {BII35}.

Restricted and negotiated procedures require a previous qualification using profile CEN WS/BII 3 {BII49} (CWA 17027-114) covered by Peppol BIS {P011} before submitting a tender. In restricted and negotiated procedures the contracting authority will send an invitation to tender using profile CEN WS/BII 3 {BII52} (CWA 17027-117) to the identified candidates which have been selected to submit a tender. In contrast, those economic operators whose qualifications are being rejected are informed using profile CEN WS/BII 3 {BII51} (CWA 17027-116).

Once the economic operator has received the call for tenders or invitation to tender, it can use the Peppol BIS {P004} for the business process of answering questions about a call for tenders. The BIS P004 is based upon CEN WS/BII3 profile {BII48} (CWA 17027-113) and supports economic operators asking questions about call for tenders. Answers of the contracting authority then have to be sent to all economic operators that subscribed to the procedure and additionally the call for tenders should be updated and pushed to the subscribers of the procedure.

In case the economic operator decides to submit a tender, he can use the Peppol BIS {P003}. After the submission of a tender, the contracting body notifies the economic operator of having received the tender. The BIS P003 is based upon CEN WS/BII3 profile {BII54} (CWA 17027-119). On the contrary, economic operators can decide to withdraw a tender that was previously submitted by using the Peppol BIS {P007}. The BIS P007 was derived from CEN WS/BII3 profile {BII53} (CWA 17027-118) and provides electronic messaging support for the economic operator to withdraw a tender. The contracting body notifies the economic operator of having received the tender withdrawal. After the tender withdrawal, an economic operator may submit a new offer at any time before the tender submission deadline.

On the opening date, the contracting authority gathers and opens all received tenders. The opening board members can now evaluate the received tenders. If questions about specific offers arise during the course of the evaluation, they can be answered through the Peppol BIS {P005}. The BIS P005 supports the contracting authority to clarify questions on a tender which has been submitted. The BIS P005 was defined according to the requirements gathered by the CEN WS/BII3 profile {BII50} (CWA 17027-115).

At the end of the evaluation process, the contracting authority needs to inform the participating economic operators upon the results of the tender evaluation. For this purpose, contracting authorities can use the Peppol BIS {P009} which provides electronic messaging support to inform the bidders that a contract has been awarded to a particular economic operator. The BIS P009 is based upon the CEN WS/BII3 profile {BII58} (CWA 17027-121). The contracting authority can use BIS P009 to inform the winner(s) at the same time as they inform the unsuccessful tenderers and they must individually declare the reasons why they failed. The notification of the awarding decision imitated by BIS P009 shall also start the standstill period clock. After the stand still period, the contracting authority can finalize the contract with the winning supplier and also send a contract award notice using BIS Peppol BIS {P008}.


