[[use-case-1]]
== Use case 1 – Request for status on a specific transport event

[cols="2,6",options="header",]
|====
|Use Case Number | 1
|*Use Case Name* a|

Request for status on a specific transport event.

|*Use Case Description* a|

The Sender sends a Transportation Status Request to ask for status on a specific transport event. The Transportation Status Type Code must be set to 1 and the event must be specified under Consignment/Transport Event.

|*Parties involved* a|

Sender +
Receiver

|*Assumptions* a|

The transport is agreed in a Transport Execution Plan or similar document. 
The sender of the Transportation Status Request has the rights to receive the type of status that is requested.

|*The flow* a|

. The Sender sends a Transportation Status Request to ask for status on a specific transport event.
. The Receiver processes the request and prepares the Transportation Status with the relevant information.
. The Receiver sends the Transportation Status to the party that sent the request.
. The requester receives the Transportation Status and takes any action based on the response.

|====