[[use-case-3-two-parties-2]]
== Use case 3 – Two Parties involved: Consignor with Multi-Pickup addresses and Carrier

[cols="2,6",options="header",]
|====
|Use Case Number | 3
|*Use Case Name* a|

Two parties involved Consignor and Carrier preparing and issuing a Transport Execution Plan Request and a Transport Execution Plan.

|*Use Case Description* a|

The Consignor provides detailed instructions to the Carrier for the transport of a consignment.

|*Parties involved* a|

Consignor +
Carrier

|*Assumptions* a|

The Consignor has a consignment to be transported and knows the type of means of transport required and has agreed terms with the Carrier for its transportation. 

The consignment has been or will be loaded into one or more specific pieces of transport equipment. 

The Consignment will be picked up from different addresses.

The Carrier has space available on a specific means of transport. The Consignor and the Carrier have a business relationship. The Consignor has ordered transportation from the Carrier.

|*The flow* a|

. The Consignor has received an Order from a Consignee.
. The Consignor sends a Transport Execution Plan Request to the Carrier.
. The Carrier accepts the Transport Execution Plan Request and confirms price and conditions with the Consignor.
. The Consignor accepts the price and terms issued by the Carrier.
. The Consignor issues a Transport Execution Plan.
. The Consignor packs the goods ready for collection by the Carrier.
. The Carrier collects the Shipments from different locations and transports it to the Consignee.

|*Remarks* a|

The Consignor provides the detailed instructions and the Consignor issues a Transport Execution Plan for the transport of a consignment.
|====