[[use-case-4]]
== Use case 4 – Request for subscription

[cols="2,6",options="header",]
|====
|Use Case Number | 4
|*Use Case Name* a|

Request for subscription.

|*Use Case Description* a|

The Sender sends a Transportation Status Request to ask for a subsctiption on status for all future deviations on planned events. The Transportation Status Type Code must be set to ????.

|*Parties involved* a|

Sender +
Receiver

|*Assumptions* a|

The transport is agreed in a Transport Execution Plan or similar document. 
The sender of the Transportation Status Request has the rights to receive the type of status that is requested.

|*The flow* a|

. The Sender sends a Transportation Status Request to ask for subsciption on status for all future deviations on planned events.
. The Receiver processes the request and prepares the Transportation Status with the relevant information.
. The Receiver sends a Transportation Status message to the party that sent the request whenever there is a deviation on an event.
. The requester receives the Transportation Statuses and takes any action based on the response.

|====