[[use-case-1]]
== Use case 1 – Consignor requests a transport from a Carrier

[cols="2,6",options="header",]
|====
|Use Case Number | 1
|*Use Case Name* a|

Consignor requests a transport from a Carrier.

|*Use Case Description* a|

Consignor in the role of Transport User provides instructions to a Carrier in the role of Transport Service Provider for the transport of a consignment.  

|*Parties involved* a|

Consignor +
Carrier

|*Assumptions* a|

The Consignor has a consignment to be transported and has agreed terms with the Carrier for its transportation. 

The Carrier has space available on a specific means of transport.

The consignment has been or will be loaded into one or more specific pieces of transport equipment. 

|*The flow* a|

. The Consignor as Transport User sends a Transport Execution Plan Request to the Carrier as Transport Service Provider.
. The Carrier replies with a Transport Execution Plan to the Consignor confirming terms and conditions for the transport.
. The Consignor packs the goods ready for collection by the Carrier.
. The Carrier collects the Shipment and transports it to the Consignee.

|====