[[use-case-3]]
== Use case 3 – Request for status on a specific transport handling unit

[cols="2,6",options="header",]
|====
|Use Case Number | 3
|*Use Case Name* a|

Request for status on a specific transport handling unit.

|*Use Case Description* a|

The Sender sends a Transportation Status Request to ask for status on a specific transport handling unit. The Transportation Status Type Code must be set to 2 and the transport handling unit must be specified under Consignment/TransportHandlingUnit.

|*Parties involved* a|

Sender +
Receiver

|*Assumptions* a|

The transport is agreed in a Transport Execution Plan or similar document. 
The sender of the Transportation Status Request has the rights to receive the type of status that is requested.

|*The flow* a|

. The Sender sends a Transportation Status Request to ask for status on a specific transport handling unit.
. The Receiver processes the request and prepares the Transportation Status with the relevant information.
. The Receiver sends the Transportation Status to the party that sent the request.
. The requester receives the Transportation Status and takes any action based on the response.

|====