[[use-case-2]]
== Use case 2 – Request for status on all transport events

[cols="2,6",options="header",]
|====
|Use Case Number | 2
|*Use Case Name* a|

Request for status on all transport events.

|*Use Case Description* a|

The Sender sends a Transportation Status Request to ask for status on all transport events up to date including the current status of the transport. The Transportation Status Type Code must be set to 4 (All execution statues).

|*Parties involved* a|

Sender +
Receiver

|*Assumptions* a|

The transport is agreed in a Transport Execution Plan or similar document. 
The sender of the Transportation Status Request has the rights to receive the type of status that is requested.

|*The flow* a|

. The Sender sends a Transportation Status Request to ask for status on all transport events.
. The Receiver processes the request and prepares the Transportation Status with the relevant information.
. The Receiver sends the Transportation Status to the party that sent the request.
. The requester receives the Transportation Status and takes any action based on the response.

|*XML example file* a|
See {examples-zip} for sample files illustrating Use Case 2.
|====