[[item_prop]]
= Additional Item Properties

Additional properties are meant for product properties that cannot be sent in any of the defined elements in the Pre-Award Catalogue. 
Additional properties consist of the Name, NameCode and/or Identity of the property and the actual Value.

.Example of additional properties:
* Color
* Nutrition +
Stated with amount per 100 g/ml.
* Genetically modified +
Legal values: True, False
* Climate Impact of the product can be sent as a property. See usecase example. 

The property can be identified by a NameCode that must be known by both sender and receiver, but better is to identify the property with an ID 
that is defined in a standard public Data Dictionary (DD) and to provide the attributes where to find the DD. 

Therefore it is recommended to use Property identification from standardised Data Dictionaries. 


.Example of use in the PreAward PreAward Catalogue message
====

[source]
----
include::../Snippets/Snippet-1.xml[tags=item-property]
----
====
