

= European Single Procurement Document (ESPD)

Article 59 of the new Public Procurement Directive 2014/24/EC introduced a new concept, the European Single Procurement Document ({link-espd}[ESPD]) which is a self-declaration document intended for preliminary evidence in a public procurement procedure. The main objective of the {link-espd}[ESPD] is to reduce the administrative burden and lead to considerable simplification of participation in public procurement procedures for buyers and suppliers. {link-espd}[ESPD] will reduce the burden by removing the need to produce a substantial number of certificates and documentation related to exclusion and selection criteria.

Documentation and services related to {link-espd}[ESPD] are provided by the European Commission. This is an overview of the currently available resources:

* link:https://github.com/ESPD/ESPD-Service[ESPD Service]
* link:https://github.com/ESPD/ESPD-EDM[ESPD Exchange Data Model]

Implementers of this profile attach ESPD Request/Response by adding a DocumentReference. The transaction T004 does not prescribe the use of a specific ESPD version. The use of specific ESPD versions by the Contracting Authority may result into incompatibilities with the systems available to the Economic Operator. Thus, it should be described by the Contracting Authority in the Tendering Documents which ESPD version is used and how it can be returned by Economic Operators. Values to indicate that an ESPD is used as part of the Call for Tenders documents are:

`cac:DocumentReference/cbc:DocumentTypeCode`

916 (Related document)

`cbc:DocumentDescription`

ESPD Request/Response

Please also see link:https://docs.peppol.eu/pracc/espd/bis/[Peppol BIS ESPD (European Single Procurement document)] for further details.
