= Definition of the procurement project

The call for tenders in this profile is intended to provide unstructured information of the procurement project. The economic operators are expected to read the provided documents and prepare their tenders following the requirements established as unstructured information.

==	Call for tenders without lots

A Call for tenders without lots has a single `cac:ProcurementProject` class. The procurement project and all the details of the project are described using the documents attached or referred using the `cac:AdditionalDocumentReference` class.

In this case, the document instance must not contain any `cac:ProcurementProjectLot` class.


The example below demonstrates the use of the `cac:ProcurementProject` class for a tendering process without lots. The structured information does not convey economic information. It is used to describe the project, to provide classification codes for main commodity and additional commodity using the Common Procurement Vocabulary link:https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/cpv[(CPV codes)] and the location where the project will be executed using the codelist for Nomenclature of Territorial Units for Statistics link:https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/nuts[(NUTS codes)].
The procurement project does not describe the tender deliverables.


[source,xml,indent=0]
.Procurement project

----
include::{xml-doc-file}[tags=ProcurementProject]

----

==	Call for tenders with lots

When the Call for tenders has to be split into lots, the `cac:ProcurementProject` class must define the overall summary of the project and there must be a `cac:ProcurementProjectLot` class per each lot.

The `cac:ProcurementProjectLot` class only requires to define the lot identifier and the name of the Lot. All the details on the lot are described as unstructured documents referred from the `cac:AdditionalDocumentReference` class.

The details of each lot are described using unstructured documents referred into the call for tenders

[source,xml,indent=0]
.{name-trans-short} with lots

----
include::{xml-doc-file}[tags=ProcurementProjectLot]

----
