[[parties]]
= Parties

The following parties/roles may be specified in the message.
The same actor may play more than one role depending on the handling routine.

[[sender-party]]
== Sender (SenderParty)

SenderParty identifies the party sending this document on the Peppol network. This is the network message sender and is not necessarily the same as the Consignor: it carries the Peppol `cbc:EndpointID`, while the Consignor is identified separately via `cac:PartyIdentification`/`cac:PartyLegalEntity`.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=sender-party]
----

[[receiver-party]]
== Receiver (ReceiverParty)

ReceiverParty identifies the party receiving this document on the Peppol network, carrying the Peppol `cbc:EndpointID` of the recipient's access point.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=receiver-party]
----

[[consignor-party]]
== Consignor (ConsignorParty)

Consignor, also known as the shipper, is the sender of the goods. The Consignor is often the buyer of the freight services. If the Consignor is the same for all consignments in the Waybill, the consignor can be described on the document level instead of in each consignment.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=consignor-party]
----

[[consignee-party]]
== Consignee (ConsigneeParty)

Consignee is known as the DeliveryCustomerParty in the Despatch and receive advice. The Consignee is the person or organisation to which the products will be shipped and who is taking possession. The role is carried out by the customer or on behalf of the customer. The Consignee is a mandatory party in the consignment element and can be the Transportation Buyer.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=consignee-party]
----

[[carrier-party]]
== Carrier (CarrierParty)

Carrier is the party providing the transport of goods between named points.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=carrier-party]
----

[[freight-forwarder-party]]
== Freight Forwarder (FreightForwarderParty)

Freight Forwarder is the party who organizes the freight transport. The freight forwarder can be the same as the carrier. For multimodal freight there can be many freight forwarders involved, one for each consignment. In this case the freight forwarder on waybill level is called the integrator.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=freight-forwarder-party]
----
