
= Business processes

The Peppol BIS Pre-Award Catalogue, when used in B2G processes, is most normally used in P003 - Tender Submission.

The pre-award catalogue transaction can also in B2G processes be used in other choreographies as qualification, DPS, mini competition and re-opening 
of competition (post-award phase).

The use of the pre-award catalogue in these other choreographies in B2G processes is not explained in detail in this document.

When used in B2B processes the Pre-Award Catalogue Request and Catalogue can be used to establish a Framework Agreement between companies as a common 
base for future business. In this case the Reference to a Contract will be missing in the Catalogue Request (RFQ) if one is used, and in the 
Catalogue itself if a RFQ is not preceding the Catalogue.  

Also, in B2B processes the transactions can be used as a RFQ and Quote based on an established Framework Agreement or without one. 


== Property 

In this document the term “property” is mentioned in several places. It is a way to describe the item when an item number is not known or it is not a 
standard product. The EO will use the requested item properties rec eived in the Pre-award Catalogue Request and reply in the Pre-award Catalogue with
an identification of the item as a Supplier's item number or a GTIN.

The property can be identified by a NameCode that must be known by both sender and receiver, but better is to identify the property with an ID that is 
defined in a standard public Data Dictionary (DD) and to provide the attributes where to find the DD. 

It is recommended to use Property identification from standardised Data Dictionaries.   
