[[use-case-3]]
== Use case 3


[cols="1,5",options="header",]
|====
|*Use Case number* |3
|*Use Case Name* |RFQ and Quote exchanged between two companies to agree on prices and terms when no previous Framework Agreement is in place.
|*Use Case Description* a|
RFQ and Quote exchanged between two companies to agree on prices and terms for a specific Project when no previous Framework Agreement is in place. 
The Delivery Address and the Delivery Period for the Project is sent in the RFQ and the products are known and identified by GTIN numbers.  

The prices in the returned Quote are stacked and depend on the actual quantity ordered. Since no Framework Agreement exists, terms are included in 
the Quote. 

Price for the Transportation to the Delivery Address is added as a separate line in the Quote that is not referring to any line in the RFQ. 

|*Parties involved* a|
Buyer (sender) (In UBL: ProviderParty) 

Seller (receiver) (In UBL: ReceiverParty)

Despatch location (In UBL: SellerSupplierParty)

Delivery location (In UBL: ContractorCustomerParty)

|*Pre conditions* a|
The Customer want to send a Catalogue Request to selected Suppliers that are relevant for this type of products. 
A framework contract does not exist between the parties.

|*Post conditions* a|
The Catalogue Request is received by the selected Suppliers.
The supplier is supposed to create and send a Catalogue as a result of this.

|*Assumptions* a|
. No framework contract is in place between the parties.
. The Supplier can provide the type of products or services requested.

|*The flow* a|
. The Customer selects which Suppliers they want to send a Catalogue Request to. 
. The Customer creates a list of products or services they want to purchase.
. The Customer forms a Catalogue Request and sends it to selected Suppliers.
. The Supplier receives the Catalogue Request and analyzes the content.
. The Supplier creates a Catalogue for the requested products containing item identification and price etc.
. The Supplier sends the Catalogue to the Customer.
. The Customer receives the Catalogue and starts the evaluation process.

|*Result* a|
. The Catalogue Request message helped the Supplier to create the Catalogue.
.. Faster.
.. With less work.
.. With less errors and misunderstandings.

. The Catalogue message helped the Customer to select the best offer.
.. Faster since Suppliers are expected to return the Catalogue quicker.
.. With less work since all Catalogues are recived in the same format and no manual entry is needed.
.. With less errors and misunderstandings.

|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 3.
|====
