[[principles-and-prerequisites]]
= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of the Logistics Advanced Despatch Advice with Response.

[[despatch-advice-message-in-general]]
== Business process in scope
This Peppol BIS supports a process for suppliers to send an Advanced Despatch Advice and for buyers to return an Advanced Despatch Advice Response. It is intended to support transmission of electronic messages for processing in automated processes by the receiver. 

The main activities supported by this BIS are:

* *Transport* Full description of how the goods are packed and delivered, or how and when the services are delivered. A delivery is taken to be a number of items that are despatched as a single consignment to a single delivery address.
* *Ordering* States what is shipped or delivered; the quantity of the delivery and what is outstanding.
* *Receiving* Full support of the process of receiving goods into a warehouse, inventory, in stores or simply at a reception counter or receiving services at agreed location
* *Responding* Response from the buyer with two alternative usages:
** a) Report status of the receipt of an Advanced Despatch Advice message
** b) Report status on the actual delivery 

:leveloffset: +1

include::../../66-advanceddespatchadvice/principles/parties.adoc[]

include::../../66-advanceddespatchadvice/principles/otherconcepts.adoc[]

//include::requirements.adoc[]

:leveloffset: -1
