
= Interoperability

This {link-peppol} BIS structure is based on the link:https://ec.europa.eu/isa2/home_en[European Interoperability Framework 2.0].

It applies the Framework as follows:

. Legal Interoperability
* Legal:
** {link-eu-directive}[Directive 2014/24/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0025&from=EN[Directive 2014/25/EU]
** link:http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014R0910&from=EN[Regulation 910/2014]

. Organizational interoperability
* Organization (Organization/Business):
** This {link-peppol} eTendering BIS supports only B2G.
** This {link-peppol} eTendering BIS supports cross border, regional and domestic tendering procedures in EU and EEA.
** This {link-peppol} eTendering BIS can function as a standardized EDI agreement within a trading community.
** This {link-peppol} eTendering BIS supports linking of business processes within the sending and receiving organization.
* Organization (Process):
** This {link-peppol} eTendering BIS supports a set of “common business processes” that are assumed to be supported by most enterprises whether public or private. These are processes that are used widely or understood as being relevant for most companies.

. Technical interoperability
* Technical Interaction (Process and semantic implementation):
** Use of transport specifications are described in the {link-eDelivery}
** Use of cryptographic specifications are described in the {link-eDocument}
