
= Key examples

The following examples show use cases illustrating how the {name-profile}  can be used.

*Example 1*

In an open procedure, after having evaluated the tenders and qualifications on basis of the exclusion, selection and award criteria the contracting body drafts an internal evaluation report. On basis of the evaluation report and the ranked list of tenders, the contracting body notifies all candidates and tenderers of the decision reached concerning the award of the contract including reasons for this decision. The system registers the start of the standstill period and archives the notifications sent to each candidate for audit purposes.

*Example 2*

After creating the opening document, the contracting body can see for the first time the tenders submitted by the economic operators. Then, using the tools available in the platform, the contracting body evaluates the received tenders and based on the pre-selected criteria they select the winner(s). As the contracting body has prepared the call for tender well, most of the calculations are made automatically, saving the contracting authority a lot of time and money. The contracting body sends out an award notice to all involved parties. After the stand still period, the contracting authority can finalize the contract with the winning supplier and also send a contract award notice to TED.
