= Changelog for spring release 2021

== v1.0.1 (Profiles P001 - P003)

*Release date 2021-05-17*

=== Maintenance of Profiles P001 - P003
Essentially editorial changes were made to the profiles to consolidate the validity of the content. No substantial changes or new features were added. All links and references to external and internal documents have been checked for validity and availability, and they have been updated if necessary. The Implementation Guidelines section of the profiles has been reworked to increase the comprehensibility of the implementation of a profile according to the underlying specifications, standards and schemas.
Since the eSENS project does not longer exist and Peppol maintains and updates the pre-award specifications now and in the future, references to the eSENS project (in profiles, transactions, schematron rules, syntax mappings and code lists) were removed to reduce confusion and contradictory statements in respect to the specifications.

* Links and references were checked for validity, availability and updated if necessary
* Implementation Guidelines have been reworked
* References to eSENS were removed or reduced


== v1.0.0 (Profiles P004 - P005)

*Release date 2021-05-17*

=== New Profile P004 - Call for Tenders Questions and Answers
The Profile P004 - "Call for Tenders Questions and Answers" was added as a new eTendering profile.  The profile describes a process providing electronic messaging support for the business process of answering questions of economic operators about a call for tenders. Thereby the profile supports contracting authorities to distribute answers to all economic operators having expressed their interest in the procedure.

* Profile P004 - "Call for Tenders Questions and Answers" was added

=== New Profile P005 - Tender Clarification
The Profile P005 - "Tender Clarification" was added as a new eTendering profile. The profile describes a process providing electronic messaging support for the business process of answering questions of contracting authorities about a tender. Thus, this profile supports the contracting authority to clarify questions on a tender which has been submitted by an economic operator.

* Profile P005 - "Tender Clarification" was added
