= Changelog for November release 2021

== v1.1.0 (Profiles P001 - P009)

*Release date 2021-11-29*

=== New profile identifers and specification identifiers for BIS P001 - P005
The structure of profile identifers and specification identifiers has been changed and aligned with Peppol Post-Award. The new BIS P006-P009 (see below) adopt the same structure. References to years and CEN BII transactions were removed to get a short, clear and comprehensive structure:

* All specification identifiers in PRAC are now expressed in the following scheme:  _urn:fdc:peppol.eu:prac:trns:x:y.z_ where "x" refers to the transaction number and "y" and "z" refer to the major and minor version number
* All profile identifiers in PRAC are now expressed in the following scheme: _urn:fdc:peppol.eu:prac:bis:x:y.z_ where "x" refers to the profile number and "y" and "z" refer to the major and minor version number


=== New scheme identifiers for electronic addresses and parties used in BIS P001 - P005
The use of scheme identifiers for electronic address identifiers and party identification has been changed from rule based schemeIDs to code list based scheme identifiers to align better with the methods used in Peppol Post-Award. The new BIS P006-P009 (see below) adopt the same structure. Corresponding examples are given in the documents. Scheme identifiers for endpoints and parties are now adopted from the following code lists:

* Electronic Address Scheme (EAS) for "Endpoint identifiers"
* ISO 6523 ICD list for "Participant identifiers"

=== Editorial changes in BIS P003
* Use of UNCL1001: Update descriptions and references to the use of Document Name Codes (UNCL1001). Clarification upon the use of codes used for Call for Tender, ESPD, Tender and REM Evidence.
* Requirements: Clarification of non-functional requirements by adding or updating br54-011, br54-007, br54-018 and br54-019

=== Version numbers of BIS P001 - P005 raised to 1.1
Since the new profile identifers and specification identifiers are a breaking change, the version number has been raised from 1.0.1 to 1.1.0 in all specification and profile IDs. The new BIS P006-P009 (see below) adopt the same version number.

=== New BIS P006 Search Notices - 1.1
The BIS P006 Search Notices - 1.1 was added as a new eTendering profile. The profile provides electronic messaging support for the business process to retrieve a bulk download of relevant notices from a publisher by any interested party.

=== New BIS P007 - Tender Withdrawal - 1.1
The BIS P006 Search Notices - 1.1 was added as a new eTendering profile. The profile provides electronic messaging support for the business process of the withdrawal of a tender or of participation in a tendering process by an economic operator.

=== New BIS P008 - Publish Notice - 1.1
The BIS P006 Search Notices - 1.1 was added as a new eTendering profile. The profile provides electronic messaging support for the business process to publish a prior information notice, a contract notice or a contract award notice. The profile is executed between a contracting body or his representative and a publication body to announce business opportunities and contract awards in public procurement procedures.

=== New BIS P009 - Notify Awarding - 1.1
The BIS P006 Search Notices - 1.1 was added as a new eTendering profile. The profile provides electronic messaging support for the business process of notification by a contracting body that a contract has been awarded to a particular economic operator.

