= Release notes for BEAst Supply 4.0
:doctype: book
:icons: font

[horizontal]
Release date:: 2022-05-31

== Initial release based on Peppol / UBL
This release is the first release based on Peppol / UBL (Universial Business Language).
The release consist of 8 transaction listed below devided into two groups.

=== Global BIS
BEAst has added documentation to make it easier for the construction industry to use Peppols global BIS and also make it easier for organizations already using the 3.1 version of BEAst to migrate to 4.0.
The rules and all the syntax is copied from the Peppol documentation. The BEAst specific documentation is prefixed by BEAst: and in the description the Peppol documentation is prefixed with Peppol: .

* Peppol Order transaction 3.2 (T01) http://bis.beast.se/4.0/syntax/Order/tree/

* Peppol Order Response transaction 3.0 (T76) http://bis.beast.se/4.0/syntax/OrderResponse/tree/

* Peppol Order Agreement 3.0 (T110) http://bis.beast.se/4.0/syntax/OrderAgreement/tree/

* Peppol Despatch Advice transaction (T16) http://bis.beast.se/4.0/syntax/DespatchAdvice/tree/

* Peppol Invoice transaction 3.0 http://bis.beast.se/4.0/syntax/Invoice/tree/

=== Logistics Incubation Project
New transactions are developed in Open Peppol incubation project. The initial versions of the transactions are developed by BEAst but will be further developed in the incubation project together with other Open Peppol members such as NOROG (Norwegiean Oil and Gas industry).

* Advanced Despatch Advice transaction 1.0 (T120) http://bis.beast.se/4.0/syntax/AdvancedDespatchAdvice/tree/

* Despatch Advice Response 1.0 (T121) http://bis.beast.se/4.0/syntax/DespatchAdviceResponse/tree/

* Weight Statement 1.0 (T122) http://bis.beast.se/4.0/syntax/WeightStatement/tree/
