= Version 1.3
[horizontal]
Release date::	May 2026
				* Date of member review:	2026-xx-xx
				* Date of publication:		2026-xx-xx
				* Mandatory to use from:	2026-xx-xx

[NOTE]
====
This is the second release update of the Peppol Logistics standard. This time only minor changes are included.
====

== New BIS documents 
* No BIS documents are added in this release.

== Updated BIS documents
* PEPPOL BIS Advanced Despatch Advice Only 1.5
** In section 6.1 explanation of a new value - "Notification only" is added in 6.1.5. Small changes in 6.1.2 too.
** A new section to explain the use of DespatchAdviceTypeCode is inserted between 6.1 and 6.2 resulting in a re-sequencing of the sections. The new section becomes 6.2 and the sections after that will be increased by 0.1.
** An explanation of how to specify a vehicle's maximum load capacity is added in section 6.6.2.
** In section 7.5 an example of using the Waste Declaration Number is added.

== New Transactions
* No transactions are added in this release.

== Updated Transactions
* Advanced Despatch Advice (T120) .......

== Updated Codelists
* DocumentStatusCode updated with new value "55 - Notification only" to be used when changes are sent after invoicing and the changes have no impact on the invoice.
* DespatchAdviceTypeCode updated with new values 101, 102, 112, 203,204, 205, 206, 207, 208, 209, 210, 211, 303, 304, 305, 308, 309, 310, 311.

== New Codelists
* No new codelists are added in this release.

== Updated Rules
* No LoC rules are changed in this version.
* Common rules are updated to PoAC version.

== New Rules
* No LoC rules are added in this release.

== Changes Use-case Example files.
* AdvancedDespatchAdviceCase_08.xml - added instance of cac:AdditionalItemProperty with WasteDeclarationNumber as the ID and the value of the property.
* AdvancedDespatchAdviceCase_08.xml - changed instance of cac:AdditionalItemProperty for TreatmentCode to show a "sub-code" - a second code.
* AdvancedDespatchAdviceCase_09.xml - added instance of cac:AdditionalItemProperty with WasteDeclarationNumber as the ID and the value of the property.
* AdvancedDespatchAdviceCase_09.xml - changed instance of cac:AdditionalItemProperty for TreatmentCode to show a "sub-code" - a second code.

== Request For Change (RFC) that are included/solved in Release 1.3
* LLC-27 Align Despatch Advice ItemInstance with Advanced Despatch Advice.
* LLC-28 Clarification of Non-Invoicing Updates and New DocumentStatusCode.
* LLC-29 Enhance DespatchAdviceTypeCode for Use Case Identification.
* LLC-30 Add Waste Declaration Number as an AdditionalItemProperty in the Advanced Despatch Advice.
* LLC-31 Add possibility to ad sub-treatment codes in existing AdditionalItemProperty already used with treatment codes for waste.
* LLC-32 Wrong description of Despatch Supplier Party in advanced despatch advice.
* LLC-33 Add BIS description for max load.
* LLC-34 LoC Rule is missing for ProfileID on Weight Statement.
* LLC-35 LoC Rule PEPPOL-T120-R002 is referenced to the wrong element in Advanced Despatch Advice.

