= Version 1.4
[horizontal]
Release date::	Nov 2026
				* Date of member review:	2026-09-25
				* Date of publication:		2026-11-25
				* Mandatory to use from:	2027-03-25

[NOTE]
====
This is the fourth release update of the Peppol Logistics standard. This time only minor changes are included.
====

== New BIS documents 
* Manifest With Application Response 0.1

== Updated BIS documents
* Peppol Waybill 1.1


== New Transactions
* * Manifest transaction (T131) is added to the Peppol Logistics BIS. The Manifest transaction is used to provide information about the contents of a shipment, including details about the items being shipped, their quantities, and any relevant documentation. This transaction is particularly useful for customs and regulatory compliance, as it allows for the electronic submission of shipment information to authorities.

== Updated Transactions
* Peppol Waybill 1.1 (T125)

* Advanced Despatch Advice (T120)
** the Licence plate delimiter in cbc:LicensePlateID is changed from semicolon (;) to hashtag (#) in line with the Peppol standard delimiter character.

== Updated Codelists
* Code Lists are updated to PoAC version.

== New Codelists
* No new codelists are added in this release.

== Updated Rules
* No LoC rules are changed in this version.
* Common rules are updated to PoAC version.

== New Rules
* No LoC rules are added in this release.

== Changes Use-case Example files.
* No changes to Use-case Example files in this release.

== Request For Change (RFC) that are included/solved in Release 1.3
* LLC-36 Licence plate delimiter update
* LLC-21  Update of Peppol Waybill – Support for the Copenhagen airport case.
* 