[[consignment]]
= Consignment

The Consignment describes how and when the goods/service has been delivered. 
If the ID is a GS1 GINC (Global Identification Number for Consignment), it should be indicated by the attribute @schemeID. If it is not,
the attribute can be omitted. The Global Identification Number for Consignment (GINC) is a number that identifies a Consignment, which is a logical grouping of goods (one or more
logistics units) transferred to a freight forwarder to be transported for a specific journey. The consignment number must be allocated by a freight
forwarder (or a carrier acting as a freight forwarder) or a consignor, but only if prior agreement of the freight forwarder is given.

The Reciver can accept or reject everything in the Consignment with a Condition code, a Reason Code and a text describing why it is rejected when rejected.
Valid Condition codes are:

* AP = Accepted, no problems found.
* CA = Accepted with claims. Description of found issues are provided.
* RE = Rejected, the whole Consignment was rejected and the goods/service not received.

.Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-2.xml[tags=consignment]
----
