[[order_line_reference]]
== Order line reference

Used to provide a reference to the purchase order on which the Advanced Despatch Advice and Receipt Advice are based. 
There may be multiple Advanced Despatch Advices to cover one purchase order and one Advanced Despatch Advice may include references to multiple orders.
When all the lines of the Advanced Despatch Advice and thus the Receipt Advice relate to the same purchase order, the order reference is indicated only in the header. 
When the lines of the Advanced Despatch Advice relate to different purchase orders, the order references must be indicated in the lines instead. 
The reference to Order Line-ID is required in the UBL syntax. To cater for scenarios where no order line reference exist a dummy value must be applied. The dummy value must consist of the characters **NA**.

.Example line level
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=orderlinereference]
----

.Example header level
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=orderreference]
----