[[receipt_line]]
= Receipt Line

Since the ReceiptLine is mandatory in UBL, we need to always include lines in the Receipt Advice.
To avoid misunderstandings, all lines in the Advanced Despatch Advice must be included in the Receipt Advice, not only the ones with a problem.
Each line contains several element and some of them are described here:

[[received_quantity]]
== Received Quantity (ReceivedQuantity)
This quantity is the whole received quantity, including also what has been rejected.

[[short_quantity]]
== Shortage Quantity (ShortQuantity)
Here is reported what is missing - how much less quantity that was received than ordered.

[[rejected_quantity]]
== Rejected Quantity (RejectedQuantity)
This quantity is a part of the Received Quantity, but for some reason it can not be used/accepted.

[[over-supply_quantity]]
== Oversupply Quantity (OversupplyQuantity)
The Oversupply Quantity is a part of the Received Quantity. If a higher quantity is received than ordered, it is reported here.

[[action_code]]
== Action Code (ActionCode)
For Shortage and Rejected Quantities there is an Action Code to inform how the customer wants the supplier to compensate.

[[reason_code]]
== Reason Code (ReasonCode)
For Rejected Quantities there is a Reason Code and a textual equivalent to inform about the reason of the rejection.

.Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=receiptline]
----
