[[response-types]]
= How the Receipt Advice is used when sending it multiple times.

The Receipt Advice can be sent multiple times as a response first to the Advanced Despatch Advice, 
then as a response to the received shipment. Which type of Receipt Advice it is, is shown by the Receipt Advice Type Code.

New updates can after that be sent if issues are found when unpacking the received goods. 

Here a summary of this:

* Confirmation of having received an Advanced Despatch Advice, but not yet validated the content (ReceiptAdviceTypeCode = "D" and DespatchDocumentReference/DocumentStatusCode = "AB").
* Confirmation of having received an Advanced Despatch Advice and validated the codes and identities which were found to be ok or not ok. (ReceiptAdviceTypeCode = "D" and DespatchDocumentReference/DocumentStatusCode = "AP" or "RE").
* Confirmation of having received the goods/service in the referred Advanced Despatch Advice. Missing or damaged Transport Handling Units can be reported, and any other issue on Consignment or Transport Handling Unit can be reported. (ReceiptAdviceTypeCode = "S" and Shipment/Consignment/Status/ConditionCode = "AP", "CA" or "RE").
* Confirmation of having received the goods/service in the referred Advanced Despatch Advice. After unpacking the Transport Handling Units new issues, like shortages or quality issues on the parts, can be found causing a new version of the Receipt Advice to be sent. (ReceiptAdviceTypeCode = "S" and ReceiptLine/ShortQuantity and/or RejectedQuantity).

The last update of the Receipt Advice is only sent if new issues are found.
