[[use-case-5-reception-shipment-rejected]]
== Use case 5 – Goods/service has arrived outside requested time window and is rejected.

This use case is based on the recommendation that a receipt of goods or service should be confirmed by a Receipt Advice.
[cols="1,5",options="header",]
|====
|*Use Case number* |5
|*Use Case Name* |Goods/service has arrived outside requested time-window and is rejected.
|*Use Case Description* a|
This is the confirmation that the goods/service has been rejected because it arrived outside time window.

The Receipt Advice enables the goods receiver to inform the supplier that the goods/service was rejected.  
This enables the Supplier to start the process of shipping the goods/service again at a new time slot.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty) 

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case).

|*Pre conditions* a|
Advanced Despatch Advice is sent from Consignor to Consignee. Receipt Advice is sent from Consignee to Consignor.

|*Post conditions* a|
Receipt advice is received by the sender of the goods.

|*Assumptions* a| 
. The Consignor and Consignee has agreed to use the Receipt Advice to confirm that the goods/service has been received or rejected.
. Earlier a Receipt Advice may have been exchanged to confirm the reception of the Advanced Despatch Advice. 
. A new Advanced Despatch Advice, starting a new process, must be issued when the goods/service is sent the next time.

|*The flow* a|
. The Advanced Despatch Advice is received by the Consignee.
. A Receipt Advice may be sent by the Consignee to confirm/reject the Advanced Despatch Advice.
. The goods/service is rejected due to late arrival.
. A Receipt Advice is created and sent by the Consignee party.
. The Consignor party receives the Receipt advice message.
. The Consignor party plan for a new delivery of the goods/service. A new Advanced Despatch Advice followed by Receipt Advice must be issued.
. The Consignee will wait for a the goods/service to arrive.

|*Result* a|
. The Receipt advice message helped the Consignee party to inform the supplier that the goods/service arrived too late and could not be received.

. The Receipt advice message helped the Consignor party know that they need to plan for a new time to deliver the goods/service.


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 5.
|====
