[[use-case-8-reception-claims-at-THU-level]]
== Use case 8 – Goods has been received with a missing Transport Handling Unit.

This use case is based on the recommendation that a receipt of goods or service should be confirmed by a Receipt Advice.
[cols="1,5",options="header",]
|====
|*Use Case number* |8
|*Use Case Name* |Goods has been received with a missing Transport Handling Unit.
|*Use Case Description* a|
This is the confirmation that the goods has arrived with a Transport Handling Unit missing.

The Receipt Advice enables the goods receiver to inform the supplier that the goods/service arrived with a Transport Handling Unit missing. 
A claim process for this will be started with the Supplier or Carrier depending on who is responsible for transportation.
(At a later stage, when the Transport Handling Units are opened and the content is checked, an updated Receipt Advice may be sent.) 
This enables the Supplier to issue the corresponding invoice and be ready for the claim process to start.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty) 

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case).

|*Pre conditions* a|
Advanced Despatch Advice is sent from Consignor to Consignee. Receipt Advice is sent from Consignee to Consignor.

|*Post conditions* a|
Receipt advice is received by the sender of the goods.

|*Assumptions* a| 
. The Consignor and Consignee has agreed to use the Receipt Advice to confirm that the goods/service has been received.
. Earlier a Receipt Advice may have been exchanged to confirm the reception of the Advanced Despatch Advice. 
. Later new Receipt Advices can be exchanged if shortages or other problems are found at a later stage.

|*The flow* a|
. The Advanced Despatch Advice is received by the Consignee.
. A Receipt Advice may be sent by the Consignee to confirm/reject the Advanced Despatch Advice.
. The goods/service is received and a damage found.
. A Receipt Advice is created and sent by the Consignee party.
. The Consignor party receives the Receipt advice message.
. The Consignor party uses the content in the Advanced Despatch Advice and Receipt Advice messages to start the invoicing process.
. The Consignor party will also be ready for the start of the claim process if the Supplier is responsible.
. The Consignee will wait for a the invoice to arrive and besides that also start the claim process with the Supplier or the Carrier.

|*Result* a|
. The Receipt advice message helped the Consignee party to inform the supplier that the goods/service was received with a missing Transport Handling Unit and that there will be a claim process for that if the supplier is responsible for transportation.

. The Receipt advice message helped the Consignor party know when to start the invoicing process, and to expect a claim from the Consignee party.


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 8.
|====
