[[use-case-2-accept-received-ADA-finally]]
== Use case 2 – Confirm the reception and the validation of an Advanced Despatch Advice.

This use case is based on the recommendation that an Advanced Despatch Advice should be confirmed as received and validated before the goods reception is made.
[cols="1,5",options="header",]
|====
|*Use Case number* |2
|*Use Case Name* |Confirm the reception and validation of an Advanced Despatch Advice.
|*Use Case Description* a|
This is the confirmation that the Advanced Despatch Advice has been received. Data checks have been made and all checked data is found to be correct.

The Receipt Advice enables the goods receiver to give a confirmation that the Advanced Despatch Advice has been received and controlled OK. 
This enables the Supplier check this step and wait for the next.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty) 

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case).

|*Pre conditions* a|
Advanced Despatch Advice is sent from Consignor to Consignee. Receipt Advice is sent from Consignee to Consignor.

|*Post conditions* a|
Receipt advice is received by the sender of the goods.

|*Assumptions* a| 
. The Consignor and Consignee has agreed to use the Receipt Advice message as a confirmation of that the Advance Despatch Advice has been received and controlled.
. Earlier a Receipt Advice may have been exchanged before any data checks were made. 
. Later new Receipt Advices can be exchanged depending on what other agreements have been made.

|*The flow* a|
. The Advanced Despatch Advice is received by the Consignee.
. If the formal validation (Peppol business rules) and the application validation 
	(Party identities, References etc.) of the Advanced Despatch Advice pass, a Receipt Advice message is sent by the Consignee's application. 
. The Consignor party receives the Receipt advice message
. The Consignor party uses the content in the Despatch advice message confirm that the Advanced Despatch Advice now has been received by the Conignee.
. The Consignee now can continue to the next step to receive the goods/service.

|*Result* a|
. The Receipt advice message helped the Consignee party to inform the supplier that the Advanced Despatch ADvice has arrived.
.. With no formal errors, no application errors
.. That the process now continues with next steps

. The Receipt advice message helped the Consignor party in the process to be sure that the Advanced Despatch Advice is received and in the process.


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 2.
|====
