[[use-case-9-reception-claims-at-line-level]]
== Use case 9 – Goods has been received ok but when opening the Transport Handling Unit there is a shortage found.

This use case is based on the recommendation that a receipt of goods or service should be confirmed by a Receipt Advice.
[cols="1,5",options="header",]
|====
|*Use Case number* |9
|*Use Case Name* |Goods has been received ok but when opening the Transport Handling Unit there is a shortage found.
|*Use Case Description* a|
This Receipt Advice is sent as an update at a later stage when the Transport Handling Units are opened and the content checked and a shortage found.

The Receipt Advice enables the goods receiver to inform the supplier that the consignment had a shortage.
A claim process for this will be started.
The supplier is requested to replace the missing parts or to create a credit note.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty) 

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case).

|*Pre conditions* a|
Advanced Despatch Advice is sent from Consignor to Consignee. Receipt Advice is sent from Consignee to Consignor.

|*Post conditions* a|
Receipt advice is received by the sender of the goods.

|*Assumptions* a| 
. The Consignor and Consignee has agreed to use the Receipt Advice to confirm that the goods/service has been received.
. Earlier a Receipt Advice may have been exchanged to confirm the reception of the Advanced Despatch Advice. 
. Earlier, at arrival of the goods, a Receipt Advice was sent to inform the Consignor about that.
. This new Receipt Advice is sent only if shortages or other problems are found at a later stage.

|*The flow* a|
. The Advanced Despatch Advice is received by the Consignee.
. A Receipt Advice may be sent by the Consignee to confirm/reject the Advanced Despatch Advice.
. The goods/service is received and confirmed.
. A Receipt Advice is created and sent by the Consignee party.
. The Consignor party receives the Receipt advice message.
. The Consignee later opens the Transport Handling Units and finds a shortage.
. A new Receipt Advice is sent by the Consignee to the Consignor informing abot the shortage.
. The Consignor party uses the content in the Receipt Advice to compensate the Consignee for the missing parts.
. The Consignee will wait for the compensation for the shortage.

|*Result* a|
. The Receipt advice message helped the Consignee to report about the shortage and to receive a compensation from the Consignor.

. The Receipt advice message helped the Consignor compensate for the missing parts.


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 9.
|====
