[[use-case-1-two-parties-1]]
== Use case 1 – Two Parties Involved: Consignor and Carrier

[cols="2,6",options="header",]
|====
|Use Case Number | 1
|*Use Case Name* a|

Two parties exchanging a Transport Execution Plan, Consignor in the role of Transport User and Carrier in the role of Transport Service Provider.

|*Use Case Description* a|

The Transport Service Provider provides detailed instructions to the Transport User for the transport of a consignment.  

|*Parties involved* a|

Consignor +
Carrier

|*Assumptions* a|

The Transport User has a consignment to be transported and knows the type of means of transport required and has agreed terms with the Carrier for its transportation. 
The Transport User and the Transport Service Provider have agreed terms for the transport in beforehand.
The consignment has been or will be loaded into one or more specific pieces of transport equipment. 
The Transport Service Provider has space available on a specific means of transport. 

|*The flow* a|

. The Consignor has received an Order from a Consignee
. The Consignor in the role of a Transport User informs the Carrier in the role of Transport Service Provider about the transport to take place.
. The Transport Service Provider sends a Transport Execution Plan to the Transport User based on agreed prices and terms.
. The Consignor packs the goods ready for collection by the Carrier.
. The Carrier collects the Shipment and transports it to the Consignee.

|====