[[use-case-1]]
== Use case 1 – Consignor and Carrier plan a transport

[cols="2,6",options="header",]
|====
|Use Case Number | 1
|*Use Case Name* a|

Consignor and Carrier plan a transport.

|*Use Case Description* a|

Consignor in the role of Transport User and Carrier in the role of Transport Service Provider exchange a Transport Execution Plan to  plan a transport of a consignment.  

|*Parties involved* a|

Consignor +
Carrier

|*Assumptions* a|

The Consignor has a consignment to be transported and has agreed terms with the Carrier for its transportation. 

The Carrier has space available on a specific means of transport.

The consignment has been or will be loaded into one or more specific pieces of transport equipment. 

|*The flow* a|

. The Carrier as Transport Service Provider sends a Transport Execution Plan to a Consignor as Transport User based on agreed terms.
. The Consignor or the Carrier may update the content of the plan by returning a Transport Execution Plan with changes.
. The Transport Execution Plan may also be cancelled by both the Consignor and the Carrier.
. The Consignor packs the goods ready for collection by the Carrier.
. The Carrier collects the Shipment and transports it to the Consignee.

|====