[[principles-and-prerequisites]]
= Principles and prerequisites

This chapter describes the principles and assumptions that underlie the use of the Logistics Advanced Despatch Advice with Receipt Advice.

[[despatch-advice-message-in-general]]
== Business process in scope
This Peppol BIS supports a process for suppliers to send an Advanced Despatch Advice and for buyers to return a Receipt Advice. It is intended to support transmission of electronic messages for processing in automated processes by the receiver. 

The main activities supported by this BIS are:

* *Transport* Full description of how the goods is packed and delivered, or how and when the services are delivered. A delivery is taken to be a number of items that are despatched as a single consignment to a single delivery address.
* *Despatch Line* States what is shipped or delivered; the quantity of the delivery and what is outstanding.
* *Validation* Buyer can accept or reject the Advanced Despatch Advice by sending the Receipt Advice as a reply to the Advanced Despatch Advice.
* *Receiving* Full support of the process of receiving goods into a warehouse, inventory, in stores or simply at a reception counter or receiving services at agreed location
* *Responding* Response from the buyer after receiving the goods/service by sending the Receipt Advice with three alternative usages:
** a) Reject the whole Consignment
** b) Accept the whole Consignment without any claim.
** c) Accept the Consignment with claims:
*** 1) Report damages at Transport Handling Units.
*** 2) Report shortage or other issues with the received products/services.

:leveloffset: +1

include::../../67-advanceddespatchadvice_w_receiptadvice/principles/parties.adoc[]

include::../../67-advanceddespatchadvice_w_receiptadvice/principles/otherconcepts.adoc[]

//include::requirements.adoc[]

:leveloffset: -1
