[[parties]]
= Parties

The following parties/roles may be specified in the message.
The same actor may play more than one role depending on the handling routine.

[[sender-party]]
== Sender (SenderParty)
The Sender is the sender of the Transport Execution Plan.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=sender-party]
----

[[receiver-party]]
== Receiver (ReceiverParty)
The Receiver is the receiver of the Transport Execution Plan. 

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=receiver-party]
----

[[transport-user-party]]
== Transport User (TransportUserParty)

The Transport User is the user of the transport service, often the consignor. The Transport User may change or cancel the Transport Execution Plan.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=transport-user-party]
----

[[transport-service-provider-party]]
== Transport Service Provider (TransportServiceProviderParty)

The Transport Service Provider is the sender of the original Transport Execution Plan and later changes to the plan.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=transport-service-provider-party]
----

[[consignor-party]]
== Consignor (ConsignorParty)

Consignor, also known as the shipper, is the sender of the goods. The Consignor is often the buyer of the freight services. If the Consignor is the same for all consignments in the Waybill, the consignor can be described on the document level instead of in each consignment.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=consignor-party]
----

[[consignee-party]]
== Consignee (ConsigneeParty)

Consignee is known as the DeliveryCustomerParty in the Despatch Advice. The Consignee is the person or organisation to which the products will be shipped and who is taking possession. The role is carried out by the customer or on behalf of the customer. The Consignee is a mandatory party in the consignment element and can be the Transportation Buyer.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=consignee-party]
----

[[billto-party]]
== Bill to party (BillToParty)

Used in the Transport Execution Plan to identify the party paying for the transport.

Example:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-1.xml[tags=billto-party]
----

