
= Business requirements

For the {link-peppol} BIS all non-functional requirements are applicable as documented in {link-bii3} {name-profile-org}. Implementers must comply to these requirements.

[cols="2,10", options="header"]
|===
| Req. ID | Requirement statement
| br51-001 | The contracting body shall inform candidates who failed to meet the exclusion and/or selection criteria of the reasons why they failed before the award decision.
             The contracting body may also inform those candidates whose qualification requests have been accepted. This should be good practice in those cases when qualification is directly followed by any invitation to tender (e.g. when using a DPS).
| br51-002 | The contracting body shall inform at least any unsuccessful tenderer simultaneously and individually of the reasons why they failed.
              In case of a positive qualification response, a reason may be left out.
| br51-003 | The contracting body shall inform any unsuccessful tenderer of the rejection of their qualification.
| br51-004 | The contracting body shall specify that the notification does not imply any commitment on behalf of the contracting body.
|===
