[[item_prop]]
= Additional Item Properties

== Definition of a property
In this document the term “property” is mentioned in several places. It is a way to describe the item when an item number is not known or it is not a 
standard product. 
The property can be identified by a Name or NameCode that must be known by both sender and receiver, but better is to identify the property with an ID 
that is defined in a standard public Data Dictionary (DD) and to provide the attributes where to find the DD. 
It is recommended to use Property identification from standardised Data Dictionaries. 

== Use of properties
Additional properties are meant for product properties that cannot be sent in any of the defined elements in PreAward Catalogue. Additional properties 
consist of the Name, NameCode and/or Identity of the property and the requested Value or Range. 

.Example of additional properties:
* Color
* Nutrition +
Stated with amount per 100 g/ml.
* Genetically modified +
Legal values: True, False

.Example of use in the PreAward Catalogue request message
include::../Snippets/Snippet-1.xml[tags=item-property]
