include::../../../shared/links.adoc[]
[[use-case-7-bulk-goods]]
== Use case 7 – Despatch Advice for bulk goods

This is a use case based on the recommended requirements for a Despatch Advice regarding a delivery of bulk goods not including the transport.
[cols="1,5",options="header",]
|====
|*Use Case number* |7
|*Use Case Name* |Despatch Advice for bulk goods
|*Use Case Description* a|
Describes a complete process whereby a Despatch party generates a Despatch Advice based on information about
delivered bulk material not including the transport.

The Despatch Advice enables the service provider to give detailed information about the service provided between the specified locations once the service has been delivered. Which enables a Buyer to reconcile the goods provided against the order.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty)

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case) 

|*Locations involved* a|
Ship-from (In UBL: DespatchAddress) (Defines the place the bulk goods is coming from.)

|*Pre conditions* a|
Bulk goods is delivered after Despatch Advice is sent. 

|*Post conditions* a|
Despatch advice is received by the receiver of the bulk goods.

|*Assumptions* a|
. The Seller has received one order from the Buyer with one (1) article (bulk goods) to be picked up.
. The Seller has accepted the order without changes.
. The Despatch party delivers the complete order as accepted


|*The flow* a|
. The Seller arrange delivery of agreed bulk goods.
. The Despatch party deliver agreed bulk goods when customer or customer's representative arrives.
. The bulk goods is weighed and a Weight statement is created.
. The Despatch party sends Despatch advice message to the Consignee.
. The Consignee party receives the Despatch advice message
. The Consignee party uses the content in the Despatch advice message to verify the delivery.


|*Result* a|
. The Despatch advice message helped the Consignee party to verify the delivery.
.. At the right time
.. At the right location
.. At the correct price

. The Despatch advice message helped the Consignee party in the process of verifying the delvery to identify the
.. Order
.. The order lines
.. The articles
.. The delivered quantity of services


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 5.
|====
