[[use-case-8-waste-treatment]]
include::../../shared/links.adoc[]
== Use case 8 – Despatch Advice for waste treatment service

This use case covers waste treatment services or similar services where the buyer brings the material to the supplier and leaves it there.
[cols="1,5",options="header",]
|====
|*Use Case number* |8
|*Use Case Name* |Despatch Advice for waste treatment service
|*Use Case Description* a|
The Despatch Advice enables the service provider (seller) to give detailed information about the service provided and the location where the material has been treated. In some cases the service provider can report the location where the material has been collected. Which enables a Buyer to reconcile, or confirm, the services provided against the order.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty)

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Different legal entity than the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Different legal entity than the Buyer in this use case) Originating party (In UBL: OriginatorCustomerParty)

|*Pre conditions* a|
Material is delivered to the seller and the services are delivered before Despatch Advice is sent. 

|*Post conditions* a|
Despatch advice is received by the receiver of the services.

|*Assumptions* a|
. The Seller has received one order from the Buyer with one (1) line for the serices to be provided.
. The Seller has accepted the order without changes.
. The Despatch party delivers the services specified in the order. 


|*The flow* a|
. The Buyer arrange delivery of material to the seller either by the sellers transport service or other carrier services.
. The Despatch party deliver agreed services.
. The Despatch party sends Despatch advice message to the Consignee
. The Consignee party receives the Despatch advice message
. The Consignee party uses the content in the Despatch advice message for confirmation of delivery.


|*Result* a|
. The Despatch advice message helped the Consignee party to confirm delivery.
.. At the right time
.. At the right location
..(At the correct price)

. The Despatch advice message helped the Consignee party in the process of confirming delvery to identify the
.. Order
.. The order lines
.. The articles
.. The delivered quantity of services


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 8.
|====
