[[use-case-4-Service]]
== Use case 4 – Services provided at one location using a vehicle.

This is a use case based on the recommended requirements for a Despatch Advice regarding a delivery of services between one one single location.
[cols="1,5",options="header",]
|====
|*Use Case number* |4
|*Use Case Name* |Services provided at one location using a vehicle.
|*Use Case Description* a|
Describes a complete process whereby a Despatch party generates a Despatch Advice based on information 
about the service provided on one single location, e.g. tasks executed by an excavator or a wheel loader.

The Despatch Advice enables the service provider to give detailed information about the service provided at the specified location once the service has been delivered. 
This enables a Buyer to reconcile the services provided against the order.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty)

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case) 

|*Pre conditions* a|
Services are delivered before Despatch Advice is sent. 

|*Post conditions* a|
Despatch advice is received by the receiver of the services.

|*Assumptions* a|
. The Seller has received one order from the Buyer with one (1) service-article to be provided on one
location, e.g executing tasks with an excavator. 
. The Seller has accepted the order without changes.
. The Despatch party delivers the complete order as accepted


|*The flow* a|
. The Seller arranges delivery of agreed services.
. The Despatch party delivers agreed services.
. The Despatch party sends Despatch advice message to the Consignee
. The Consignee party receives the Despatch advice message
. The Consignee party uses the content in the Despatch advice message to verify the delivery of the service.


|*Result* a|
. The Despatch advice message helped the Consignee party to verify delivery.
.. At the right time
.. At the right location
.. At the correct price

. The Despatch advice message helped the Consignee party in the process of verifying the delvery to identify the
.. Order
.. The order lines
.. The articles
.. The delivered quantity of services and the price.


|*XML example file* a|
See Appendix A for a sample file illustrating Use Case 4.
|====
