[[use-case-3-services-at-one-location]]
== Use case 3 – Despatch Advice for services provided at one location without vehicle

This is a use case based on the recommended requirements for a Despatch Advice regarding a delivery of services on one single location.
[cols="1,5",options="header",]
|====
|*Use Case number* |3
|*Use Case Name* |Despatch Advice for services provided at one location without vehicle
|*Use Case Description* a|
Describes a complete process whereby a Despatch party generates a Despatch Advice based on information 
about the service provided at one location when a vehicle is not required, e.g. build scaffolding or build fences.

The Despatch Advice enables the service provider to give detailed information about the service provided 
at the specified location once the service has been delivered. 
This enables the Buyer to reconcile the services provided against the order.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty)

Seller (In UBL: SellerSupplierParty)

Despatch party (In UBL: DespatchSupplierParty) (Same legal entity as the Seller in this use case)

Consignee party (In UBL: DeliveryCustomerParty) (Same legal entity as the Buyer in this use case) 

|*Pre conditions* a|
Services are delivered for a period of time before Despatch Advice is sent. 

|*Post conditions* a|
Despatch advice is received by the receiver of the services.

|*Assumptions* a|
. The Seller has received one order from the Buyer with one (1) article to be provided at a specified location, e.g building a fence around a property.
. The Seller has accepted the order without changes.
. The Despatch party delivers the complete order as accepted



|*The flow* a|
. The Seller arange delivery of agreed services.
. The Despatch party deliver agreed services.
. The Despatch party sends Despatch advice message to the Consignee when ready with the order.
. The Consignee party receives the Despatch advice message
. The Consignee party uses the content in the Despatch advice message for validating against the order.


|*Result* a|
. The Despatch advice message helped the Consignee party to check delivery against the order.
.. At the right time
.. At the right location
.. At the correct price

. The Despatch advice message helped the Consignee party in the process of confirming delvery to identify the
.. Order
.. The order lines
.. The articles
.. The delivered quantity of services


|*XML example file* a|
See Appendix A for a sample file illustrating Use Case 3.
|====
