[[use-case-11-transport-of-non-bulk-goods]]
== Use case 11 – Despatch Advice for transport of non-bulk goods (service only)

The use case covers transport of non-bulk goods and other types of transports that does not need a weight statement. e.g. pallets, bundles, containers, vehicles etc. 
Note that the use case only covers the transprotation service, if the despach advice also covers material, additional information needs to be added from the relevant use cases.
[cols="1,5",options="header",]
|====
|*Use Case number* |11
|*Use Case Name* |Despatch Advice for transport of non-bulk goods (service only)
|*Use Case Description* a|
Describes a complete process whereby a Despatch party (the service provider) generates a Despatch Advice based on information about the service provided of non-bulk goods transport between two locations.

The Despatch Advice enables the service provider to give detailed information about the service provided between the specified locations once the service has been delivered. Which enables a Buyer to reconcile, or confirm, the services provided against the order.

|*Parties involved* a|
Buyer (In UBL: BuyerCustomerParty)

Seller (In UBL: SellerSupplierParty)

|*Pre conditions* a|
Services are delivered before Despatch Advice is sent. 

|*Post conditions* a|
Despatch advice is received by the receiver of the services.

|*Assumptions* a|
. The Seller has received one order from the Buyer with one (1) line describing the service to be provided between two locations, e.g transport of goods between locations A and B. 
. The Seller (transporter) has accepted the order without changes.
. The Despatch party delivers the complete order as accepted


|*The flow* a|
. The Seller arange delivery of agreed services.
. The Seller party deliver agreed services.
. The Seller party sends Despatch advice message to the Buyer
. The Buyer party receives the Despatch advice message
. The Buyer party uses the content in the Despatch advice message for confirmation of delivery.


|*Result* a|
. The Despatch advice message helped the Buyer party to confirm the serivce delivered.
.. At the right time
.. At the right location
..(At the correct price)

. The Despatch advice message helped the Buyer party in the process of confirming delvery to identify the
.. Order
.. The order lines
.. The articles
.. The delivered quantity of services


|*XML example file* a|
See {examples-zip} for a sample file illustrating Use Case 11.
|====
